/**
 * Rendered files. Each render writes to a private temporary name and renames
 * it into place only on success, so a failure never deletes a file the caller
 * owned. Generated outputs in the default output directory are pruned after
 * each successful render so they do not accumulate forever.
 */
import { randomUUID } from "node:crypto";
import { readdir, rename, rm, stat } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

/** Keep generated outputs for a day, and never more than the newest 30. */
export const OUTPUT_RETENTION = { maxAgeMs: 24 * 60 * 60 * 1000, keep: 30 } as const;

/** Only files Core generated under its default names are ever pruned. */
const GENERATED = /^(?:card|template)-[0-9a-f-]{36}\.(?:png|gif|mp4)$/;

const PARTIAL = /^\.partial-[0-9a-f-]{36}-/;

/** A sibling temp path for `final`; same directory so the rename is atomic.
 * It keeps the real extension, which the engine uses to pick an encoder. */
export function stagingPath(final: string): string {
  return join(dirname(final), `.partial-${randomUUID()}-${basename(final)}`);
}

/** Write through `produce(temp)`, then move the result to `final`. The temp
 * file is removed on failure; `final` is untouched unless the run succeeded. */
export async function writeOutput<T>(final: string, produce: (temp: string) => Promise<T>): Promise<T> {
  const temp = stagingPath(final);
  try {
    const result = await produce(temp);
    await rename(temp, final);
    return result;
  } catch (error) {
    await rm(temp, { force: true });
    throw error;
  }
}

/** Delete generated outputs in `dir` older than the age limit or beyond the
 * newest `keep`. `protect` (the output just produced) is never removed.
 * Best effort: pruning never fails a render. Returns the removed names. */
export async function pruneOutputs(dir: string, protect?: string, retention: { maxAgeMs: number; keep: number } = OUTPUT_RETENTION, now = Date.now()): Promise<string[]> {
  let names: string[];
  try { names = await readdir(dir); } catch { return []; }
  const files: { name: string; mtime: number }[] = [];
  for (const name of names) {
    // Stale `.partial` files from a killed run are also generated by us.
    const partial = PARTIAL.test(name) && GENERATED.test(name.replace(PARTIAL, ""));
    if (!GENERATED.test(name) && !partial) continue;
    try { files.push({ name, mtime: (await stat(join(dir, name))).mtimeMs }); } catch { /* raced */ }
  }
  files.sort((a, b) => b.mtime - a.mtime);
  const removed: string[] = [];
  const kept = new Set<string>();
  for (const file of files) {
    const path = join(dir, file.name);
    const isPartial = PARTIAL.test(file.name);
    // A partial may belong to a render still in progress; only age removes it.
    const tooOld = now - file.mtime > retention.maxAgeMs;
    const tooMany = !isPartial && kept.size >= retention.keep;
    if (path === protect || (!tooOld && !tooMany)) { if (!isPartial) kept.add(file.name); continue; }
    try { await rm(path, { force: true }); removed.push(file.name); } catch { /* best effort */ }
  }
  return removed;
}
