/**
 * Lyric motion, the film: a planned program (lyric-video.ts) as Pocket Motion
 * nodes and baked keyframes.
 *
 * - Every cut is gated in time (shown when its transition starts, hidden when
 *   the next cut covers it) and nests: ground → shapes → decorative text →
 *   an exit wrapper → a hold wrapper (drift, float, breathe, jitter) → the
 *   chromatic ghost passes and the entrance (per glyph, per plate, or a wipe
 *   or slices of the whole block) → the glyphs; then notes, a flash, the
 *   signature.
 * - Koma-uchi: a style with `koma` 12 has every motion sampled at 12
 *   drawings a second and held between them (pairs of keyframes, linear);
 *   the engine has no steps() easing. Delays snap to the same 1/12 s grid,
 *   so everything on screen changes on the same frames.
 * - Beat: ghosts spike and decor pulses once per beat of the style's tempo.
 * - Type plates are images: this module places them (type-raster.ts
 *   geometry) and lists them; composeLyrics draws the pixels.
 * - Textures (grain, scanlines, paper, vignette) lie over everything; their
 *   images are generated by lyric-texture.ts.
 */
import { join } from "node:path";
import { splitEmoji } from "../render/emoji.ts";
import { CODE_FONT_DIR, TEMPLATE_FACES, TEXT_FONT, paintClasses, softFill, type TemplateLayout, type TemplateLine, type TemplateMeasure, type TemplateRect } from "./compose.ts";
import { loadFace, plateGeometry, type PlateStyle } from "./type-raster.ts";
import { generator, graphemes, LYRICS_MOTION, LYRICS_STYLES, LYRICS_TIMING, seedOf, withAlpha, type Box, type LyricsProgram, type LyricsVariant } from "./lyrics.ts";

export interface PlateRequest { readonly file: string; readonly font: string; readonly text: string; readonly size: number; readonly style: PlateStyle }
export interface LyricsComposition {
  readonly body: string;
  readonly keyframes: Record<string, unknown>;
  readonly animations: Record<string, { value: string }>;
  readonly frames: number;
  readonly emojiKeys: Set<string>;
  /** Type plates to draw into the composition directory. */
  readonly plates: readonly PlateRequest[];
  /** Texture images to generate (lyric-texture.ts). */
  readonly textures: readonly { readonly file: string; readonly kind: "grain" | "scanlines" | "paper"; readonly width: number; readonly height: number; readonly alpha: number }[];
}

type Props = Record<string, number | string>;
/** Units per animated property; the rest are unitless or colours. */
const UNIT: Record<string, string> = { translateX: "px", translateY: "px", blur: "px", rotate: "deg", textStrokeWidth: "px", dropShadowBlur: "px" };
const fmt = (key: string, v: number | string) => (typeof v === "string" ? v : `${Math.round(v * 1000) / 1000}${UNIT[key] ?? ""}`);

/* ───────────── Easing ───────────── */
interface Ease { readonly css: string; readonly f: (t: number) => number }
function bezier(x1: number, y1: number, x2: number, y2: number): Ease {
  const cx = 3 * x1, bx = 3 * (x2 - x1) - cx, ax = 1 - cx - bx, cy = 3 * y1, by = 3 * (y2 - y1) - cy, ay = 1 - cy - by;
  const sx = (t: number) => ((ax * t + bx) * t + cx) * t, sy = (t: number) => ((ay * t + by) * t + cy) * t;
  const f = (x: number) => {
    if (x <= 0) return 0;
    if (x >= 1) return 1;
    let t = x;
    for (let i = 0; i < 8; i++) { const e = sx(t) - x; const d = (3 * ax * t + 2 * bx) * t + cx; if (Math.abs(e) < 1e-5 || Math.abs(d) < 1e-6) break; t -= e / d; }
    let lo = 0, hi = 1;
    if (Math.abs(sx(t) - x) > 1e-4) { t = x; for (let i = 0; i < 30; i++) { if (sx(t) < x) lo = t; else hi = t; t = (lo + hi) / 2; } }
    return sy(t);
  };
  return { css: `cubic-bezier(${x1},${y1},${x2},${y2})`, f };
}
const EASE = {
  out: bezier(0.16, 1, 0.3, 1), back: bezier(0.34, 1.56, 0.64, 1), inOut: bezier(0.65, 0, 0.35, 1), in: bezier(0.5, 0, 0.75, 0),
  soft: bezier(0.25, 0.1, 0.25, 1), linear: { css: "linear", f: (t: number) => t } as Ease,
};

/* ───────────── Animation baking ───────────── */
class Film {
  readonly keyframes: Record<string, unknown> = {};
  readonly animations: Record<string, { value: string }> = {};
  private count = 0;
  private readonly names = new Map<string, string>();
  /** One step of koma-uchi in ms (0: smooth). */
  readonly step: number;
  constructor(koma: number) { this.step = koma ? 1000 / koma : 0; }
  private key(frames: Record<string, Props>): string {
    const body: Record<string, Record<string, string>> = {};
    for (const [at, props] of Object.entries(frames)) body[at] = Object.fromEntries(Object.entries(props).map(([k, v]) => [k, fmt(k, v)]));
    const json = JSON.stringify(body);
    let name = this.names.get(json);
    if (!name) { name = `k${this.names.size}`; this.names.set(json, name); this.keyframes[name] = body; }
    return name;
  }
  /** Snap a delay to the koma grid. */
  at(ms: number): number { return this.step ? Math.round(ms / this.step) * this.step : ms; }
  /**
   * One animation: `stops` (progress 0..1 → props, first and last pinning
   * every property) over `dur` ms after `delay`, eased per segment. Stepped
   * when the film has koma (or `stepped` asks for it): sampled on the step
   * grid and held between samples. `iterations` repeats it (0 = forever).
   */
  track(stops: readonly (readonly [number, Props])[], dur: number, delay: number, ease: Ease = EASE.out, opts: { iterations?: number; stepped?: boolean; step?: number } = {}): string {
    const step = opts.step ?? (opts.stepped || this.step ? this.step || 1000 / 12 : 0);
    const it = opts.iterations === undefined ? "" : opts.iterations === 0 ? " infinite" : ` ${opts.iterations}`;
    if (!step) {
      const frames: Record<string, Props> = {};
      for (const [p, props] of stops) frames[pct(p)] = props;
      return `${this.key(frames)} ${ms(dur)} ${ease.css} ${ms(delay)}${it} both`;
    }
    const n = Math.max(1, Math.round(dur / step));
    const total = n * step;
    const frames: Record<string, Props> = {};
    const value = (p: number): Props => {
      let k = 0;
      while (k + 1 < stops.length - 1 && stops[k + 1]![0] <= p) k++;
      const [p0, a] = stops[k]!, [p1, b] = stops[Math.min(k + 1, stops.length - 1)]!;
      const t = p1 > p0 ? ease.f(Math.min(1, Math.max(0, (p - p0) / (p1 - p0)))) : 1;
      const out: Props = {};
      for (const [key, v] of Object.entries(a)) {
        const w = b[key];
        out[key] = typeof v === "number" && typeof w === "number" ? v + (w - v) * t : t < 1 ? v : (w ?? v);
      }
      return out;
    };
    for (let k = 0; k < n; k++) {
      const v = value(k / n);
      frames[pct(k / n)] = v;
      // Held until one engine tick (1/60 s) before the next drawing: keyframes closer than a tick bake wrong.
      frames[pct((k + 1) / n - TICK / total)] = v;
    }
    frames["100%"] = value(1);
    return `${this.key(frames)} ${ms(total)} linear ${ms(opts.stepped || this.step ? Math.round(delay / step) * step : delay)}${it} both`;
  }
  /** The class token binding one or more animation parts to a node. */
  use(parts: readonly string[]): string {
    parts = parts.filter(Boolean);
    if (!parts.length) return "";
    const name = `l${this.count++}`;
    this.animations[name] = { value: parts.join(", ") };
    return ` animate-${name}`;
  }
}
/** The engine bakes timelines at 60 Hz. */
const TICK = 1000 / 60;
const pct = (p: number) => `${Math.round(Math.min(1, Math.max(0, p)) * 10000) / 100}%`;
const ms = (n: number) => `${Math.max(0, Math.round(n))}ms`;
const px = (n: number) => `${Math.round(n * 100) / 100}px`;

/* ───────────── Nodes ───────────── */
const view = (box: Box, extra: string, children: readonly string[]) =>
  `<View class="absolute left-[${px(box.x)}] top-[${px(box.y)}] w-[${px(box.width)}] h-[${px(box.height)}]${extra}">\n${children.join("\n")}\n</View>`;
const rectNode = (r: TemplateRect, dx: number, dy: number, extra = "") =>
  `<View class="absolute left-[${px(r.x - dx)}] top-[${px(r.y - dy)}] w-[${px(r.width)}] h-[${px(r.height)}] ${r.soft ? softFill(r.color, r.soft) : `bg-[${r.color}]`} rounded-[${px(r.radius)}]${extra}" />`;

/** The file a plate is drawn into: its content decides the name. */
function plateFile(font: string, text: string, size: number, style: PlateStyle): string {
  let h = seedOf(JSON.stringify([font.split("/").pop(), text, size, style]));
  h = (h ^ seedOf(`${text}\u0000${size}`)) >>> 0;
  return `lp_${h.toString(36)}_${size}.png`;
}
function fontOf(line: TemplateLine): string {
  if (line.face && TEMPLATE_FACES[line.face]) return join(CODE_FONT_DIR, TEMPLATE_FACES[line.face]!.regular);
  return join(CODE_FONT_DIR, line.bold ? TEXT_FONT.bold : TEXT_FONT.regular);
}

/** Where a plate line's image goes (its box's top-left for an unturned plate: the em box on the baseline; the box centre for a turned one) and what to draw. */
export function placePlate(line: TemplateLine, color = line.color, extra: Partial<PlateStyle> = {}): { left: number; top: number; width: number; height: number; request: PlateRequest } {
  const font = fontOf(line);
  const face = loadFace(font);
  // Gradient ink and a thickening outline come from the line's paint (a ghost pass keeps its flat colour).
  const paint = color === line.color ? line.paint : undefined;
  const stroke = line.plate?.stroke ?? (paint?.stroke && !paint.stroke.hollow ? { width: paint.stroke.width, color: paint.stroke.color } : undefined);
  const st: PlateStyle = { color, ...(line.plate?.rotate ? { rotate: line.plate.rotate } : {}), ...(line.plate?.alpha !== undefined ? { alpha: line.plate.alpha } : {}),
    ...(stroke ? { stroke } : {}), ...(paint?.gradient ? { gradient: paint.gradient } : {}), ...extra };
  const g = plateGeometry(face, line.text, line.size, st);
  const [left, top] = line.plate?.rotate ? [line.x + line.width / 2 - g.cx, line.y + line.height / 2 - g.cy] : [line.x - g.ox, line.y + line.size * 0.88 - g.oy];
  return { left, top, width: g.width, height: g.height, request: { file: plateFile(font, line.text, line.size, st), font, text: line.text, size: line.size, style: st } };
}

/** The lyric video as Pocket Motion nodes and baked animations. */
export function lyricsComposition(layout: TemplateLayout, program: LyricsProgram, measure: TemplateMeasure, variant: LyricsVariant): LyricsComposition {
  const V = LYRICS_MOTION[variant], style = LYRICS_STYLES[variant];
  const W = layout.width, H = program.frameHeight;
  const film = new Film(program.koma);
  const emojiKeys = new Set<string>();
  const plates: PlateRequest[] = [];
  const random = generator(seedOf(`${layout.lines.map((l) => l.text).join("")}\u0000film\u0000${variant}`));
  const light = (hex: string) => { const n = parseInt(hex.slice(1, 7), 16); return (0.2126 * (n >> 16) + 0.7152 * ((n >> 8) & 255) + 0.0722 * (n & 255)) / 255 > 0.55; };

  /** An engine glyph: Text (or an emoji Image) at (x, y) in its parent. */
  const glyphNode = (text: string, x: number, y: number, line: TemplateLine, ink: string, anim: string) => {
    const emoji = splitEmoji(text).find((run) => "emoji" in run);
    if (emoji && "emoji" in emoji) {
      emojiKeys.add(emoji.key);
      return `<Image class="absolute left-[${px(x)}] top-[${px(y + (line.height - line.size) / 2)}] w-[${line.size}px] h-[${line.size}px]${anim}" src="e_${emoji.key}.png" />`;
    }
    return `<Text class="absolute left-[${px(x)}] top-[${px(y)}] text-[${line.size}px] ${line.bold && !line.face ? "font-bold" : ""}${line.face ? ` font-[${line.face}]` : ""} ${ink} h-[${px(line.height)}]${anim}">{${JSON.stringify(text)}}</Text>`;
  };
  /** A plate image of `line` in `color` (or the line's own), placed at its box, relative to (dx, dy). */
  const plateNode = (line: TemplateLine, dx: number, dy: number, anim: string, color = line.color, extra: Partial<PlateStyle> = {}): string => {
    const placed = placePlate(line, color, extra);
    if (!plates.some((p) => p.file === placed.request.file)) plates.push(placed.request);
    return `<Image class="absolute left-[${px(placed.left - dx)}] top-[${px(placed.top - dy)}] w-[${placed.width}px] h-[${placed.height}px]${anim}" src="${placed.request.file}" />`;
  };
  /** Glyph positions of an engine line (tracking included). */
  const positions = (line: TemplateLine): { g: string; x: number }[] => {
    const out: { g: string; x: number }[] = [];
    let prefix = "", k = 0;
    const base = line.offset ? line.x + line.offset.x : line.x;
    for (const g of graphemes(line.text)) {
      const x = base + (line.offset ? 0 : measure.width(prefix, line.size, line.bold, line.face)) + (line.tracking ?? 0) * line.size * k;
      prefix += g; k++;
      if (g.trim()) out.push({ g, x });
    }
    return out;
  };

  const signature = layout.lines.filter((l) => l.signature);
  const nodes: string[] = [];
  for (const [i, cut] of program.cuts.entries()) {
    const last = i === program.cuts.length - 1;
    const p = cut.palette, S = film.at(cut.start);
    const holdEnd = last ? program.durationMs : cut.end;
    const size = cut.glyphSize;
    const inner: string[] = [];
    const full = { x: 0, y: 0, width: W, height: H };
    /* Ground and transition. */
    const ground = layout.shapes[cut.ground]!;
    const tMs = Math.max(0, cut.start - cut.inAt);
    const tr = cut.transition;
    const groundParts: string[] = [];
    if (tr === "fade") groundParts.push(film.track([[0, { opacity: 0 }], [1, { opacity: 1 }]], tMs, cut.inAt, EASE.inOut));
    else if (tr.startsWith("wipe-")) {
      const from: Props = tr === "wipe-l" ? { translateX: -W } : tr === "wipe-r" ? { translateX: W } : tr === "wipe-u" ? { translateY: H } : { translateY: -H };
      const to: Props = Object.fromEntries(Object.keys(from).map((k) => [k, 0]));
      groundParts.push(film.track([[0, from], [1, to]], tMs, cut.inAt, EASE.inOut));
    }
    else if (tr === "slice") groundParts.push(film.track([[0, { opacity: 0 }], [0.98, { opacity: 0 }], [1, { opacity: 1 }]], tMs, cut.inAt, EASE.linear));
    inner.push(rectNode(ground, 0, 0, film.use(groundParts)));
    // A colour swap: the new ground shows in its ink for part of the transition, then its own colour.
    if (tr === "swap") inner.push(rectNode({ ...ground, color: p.ink }, 0, 0, film.use([film.track([[0, { opacity: 1 }], [0.6, { opacity: 1 }], [0.61, { opacity: 0 }], [1, { opacity: 0 }]], tMs, cut.inAt, EASE.linear, { stepped: true })])));
    if (tr === "slice") {
      const n = 4, bh = Math.ceil(H / n);
      for (let k = 0; k < n; k++) {
        const band: TemplateRect = { x: 0, y: k * bh, width: W, height: bh + 1, color: p.bg, radius: 0 };
        const from = k % 2 ? W : -W;
        inner.push(rectNode(band, 0, 0, film.use([film.track([[0, { translateX: from }], [1, { translateX: 0 }]], Math.max(120, tMs - 60), cut.inAt + k * 20, EASE.out)])));
      }
    }
    /* Shapes under the lyric. */
    const shapeNode = (s: LyricsProgram["cuts"][number]["shapes"][number]) => {
      const r = layout.shapes[s.shape]!;
      const d = S + s.delay;
      const rot: Props = s.rotate ? { rotate: s.rotate } : {};
      let parts: string[] = [];
      let origin = "";
      const grow = (key: "scaleX" | "scaleY") => film.track([[0, { [key]: 0, ...rot }], [1, { [key]: 1, ...rot }]], 380, d, EASE.out);
      switch (s.motion) {
        case "slide-l": parts = [film.track([[0, { translateX: -W, ...rot }], [1, { translateX: 0, ...rot }]], 420, d, EASE.out)]; break;
        case "slide-r": parts = [film.track([[0, { translateX: W, ...rot }], [1, { translateX: 0, ...rot }]], 420, d, EASE.out)]; break;
        case "slide-u": parts = [film.track([[0, { translateY: H, ...rot }], [1, { translateY: 0, ...rot }]], 420, d, EASE.out)]; break;
        case "slide-d": parts = [film.track([[0, { translateY: -H, ...rot }], [1, { translateY: 0, ...rot }]], 420, d, EASE.out)]; break;
        case "grow-x": origin = " origin-left"; parts = [grow("scaleX")]; break;
        case "grow-x-r": origin = " origin-right"; parts = [grow("scaleX")]; break;
        case "grow-x-c": parts = [grow("scaleX")]; break;
        case "grow-y": origin = " origin-top"; parts = [grow("scaleY")]; break;
        case "pop": parts = [film.track([[0, { scale: 0, ...rot }], [0.6, { scale: 1.08, ...rot }], [1, { scale: 1, ...rot }]], 420, d, EASE.out)]; break;
        case "fade": parts = [film.track([[0, { opacity: 0, ...rot }], [1, { opacity: 1, ...rot }]], 360, d, EASE.soft)]; break;
        case "pulse": parts = [film.track([[0, { scale: 1.06, ...rot }], [1, { scale: 1, ...rot }]], program.beatMs, S, EASE.out, { iterations: Math.max(1, Math.ceil((holdEnd - S) / program.beatMs)) })]; break;
        default: if (s.rotate) parts = [film.track([[0, rot], [1, rot]], 17, 0, EASE.linear, { step: 0 })];
      }
      return rectNode(r, 0, 0, `${origin}${film.use(parts)}`);
    };
    for (const s of cut.shapes) if (!s.over) inner.push(shapeNode(s));
    /* Decorative text (ghost repeats, tickers, the big numeral): under the lyric. */
    for (const d of cut.decor) {
      const line = layout.lines[d.line]!;
      const at = S + d.delay;
      let parts: string[];
      switch (d.motion) {
        case "rise": parts = [film.track([[0, { opacity: 0, translateY: line.size * 0.4 }], [1, { opacity: 1, translateY: 0 }]], 520, at, EASE.out)]; break;
        case "settle": parts = [film.track([[0, { opacity: 0, scale: 1.12 }], [0.12, { opacity: 1, scale: 1.08 }], [1, { opacity: 1, scale: 1 }]], Math.max(600, holdEnd - at), at, EASE.soft)]; break;
        case "scroll-l": case "scroll-r": {
          const dist = (d.motion === "scroll-l" ? -1 : 1) * W * 0.35 * Math.max(1, (holdEnd - S) / 3000);
          parts = [film.track([[0, { translateX: 0 }], [1, { translateX: dist }]], Math.max(600, holdEnd - S), S, EASE.linear, { step: film.step })];
          break;
        }
        default: parts = [film.track([[0, { opacity: 0 }], [1, { opacity: 1 }]], 420, at, EASE.soft)];
      }
      const anim = film.use(parts);
      if (line.plate) inner.push(plateNode(line, 0, 0, anim));
      else {
        const run = positions(line).map(({ g, x }) => glyphNode(g, x - line.x, 0, line, paintClasses(line.paint, line.color), ""));
        inner.push(view({ x: line.x, y: line.y, width: Math.max(1, line.width), height: line.height }, anim, run));
      }
    }
    /* The lyric. */
    const outer = cut.outer;
    const textLines = cut.text.map((k) => layout.lines[k]!);
    const n = textLines.reduce((c, l) => c + (l.plate ? 1 : graphemes(l.text).filter((g) => g.trim()).length), 0);
    const entrance = cut.entrance;
    const block = entrance === "wipe" || entrance === "slice";
    const typing = entrance === "type";
    const window = typing || block ? 0 : Math.min(V.maxStaggerMs, cut.hold * 0.4, V.staggerMs * Math.max(0, n - 1));
    const enterMs = Math.max(200, Math.min(V.enterMs, cut.hold * 0.7 - window));
    const typeStep = Math.min(V.typeMs, (cut.hold * 0.6) / Math.max(1, n));
    const revealEnd = S + (typing ? typeStep * n : block ? 520 : window + enterMs);
    const blur = style.engine.blur;
    /** Per-glyph (or per-plate) entrance for item k at size s. */
    const enter = (k: number, s: number, plate: boolean): string => {
      if (block) return "";
      const delay = typing ? S + k * typeStep : S + (n > 1 ? (window * k) / (n - 1) : 0);
      const b = blur && !plate && !typing && program.koma === 0 ? Math.round(s * blur.entranceEm * 10) / 10 : 0;
      const f = (props: Props): Props => (b ? { ...props, blur: props.opacity === 0 ? b : 0 } : props);
      switch (entrance) {
        case "type": return film.track([[0, { opacity: 0 }], [0.01, { opacity: 1 }], [1, { opacity: 1 }]], 34, delay, EASE.linear, { step: 0 });
        case "rise": return film.track([[0, f({ opacity: 0, translateY: s * V.riseEm })], [1, f({ opacity: 1, translateY: 0 })]], enterMs, delay, EASE.out);
        case "drop": { const dd = s * V.dropEm; return film.track([[0, f({ opacity: 0, translateY: -dd })], [0.45, { opacity: 1, translateY: dd * 0.14, ...(b ? { blur: 0 } : {}) }], [0.72, { opacity: 1, translateY: -dd * 0.05, ...(b ? { blur: 0 } : {}) }], [1, f({ opacity: 1, translateY: 0 })]], enterMs + 100, delay, EASE.out); }
        case "slide": return film.track([[0, f({ opacity: 0, translateX: -s * V.slideEm })], [1, f({ opacity: 1, translateX: 0 })]], enterMs, delay, EASE.out);
        case "pop": return plate
          ? film.track([[0, { opacity: 0, scale: 0.2 }], [0.55, { opacity: 1, scale: 1.18 }], [1, { opacity: 1, scale: 1 }]], enterMs + 60, delay, EASE.out)
          : film.track([[0, { opacity: 0, translateY: s * 0.45 }], [0.6, { opacity: 1, translateY: -s * 0.1 }], [1, { opacity: 1, translateY: 0 }]], enterMs + 60, delay, EASE.out);
        case "zoom": return plate
          ? film.track([[0, { opacity: 0, scale: 1.7 }], [1, { opacity: 1, scale: 1 }]], enterMs + 80, delay, EASE.out)
          : film.track([[0, f({ opacity: 0 })], [1, f({ opacity: 1 })]], Math.min(enterMs, 360), delay, EASE.soft);
        case "flicker": {
          const r = generator(seedOf(`${i}\u0000${k}`));
          const stops: [number, Props][] = [];
          const steps = 5;
          for (let j = 0; j < steps; j++) stops.push([j / steps, { opacity: j === steps - 1 ? 1 : r() < 0.5 ? 0 : 0.85 }]);
          stops.push([1, { opacity: 1 }]);
          stops[0] = [0, { opacity: 0 }];
          return film.track(stops, steps * (1000 / 12), delay, EASE.linear, { stepped: true });
        }
        case "focus": return film.track([[0, { opacity: 0, blur: Math.max(4, Math.round(s * 0.12)) }], [1, { opacity: 1, blur: 0 }]], enterMs + 120, delay, EASE.soft);
        default: return film.track([[0, { opacity: 0 }], [1, { opacity: 1 }]], enterMs, delay, EASE.soft);
      }
    };
    // Glyph nodes (relative to the outer box) and the matching ghost copies.
    const main: string[] = [], ghostA: string[] = [], ghostB: string[] = [];
    let order = 0;
    const punchAt = revealEnd + 60;
    const cursorStops: { t: number; left: number; x: number; y: number; h: number }[] = [];
    for (const line of textLines) {
      if (line.plate) {
        const anim = film.use([enter(order++, line.size, true)]);
        if (line.emphasis && !block) {
          // The emphasised glyph jumps in size as the line lands (a wrapper, so the entrance keeps its own scale).
          const r = { x: line.x - outer.x, y: line.y - outer.y, width: line.width, height: line.height };
          const jump = film.track([[0, { scale: 1 }], [0.3, { scale: 1.32 }], [0.62, { scale: 0.96 }], [1, { scale: 1 }]], V.punchMs, punchAt + order * 30, EASE.out);
          main.push(view(r, film.use([jump]), [plateNode(line, line.x, line.y, anim)]));
        } else main.push(plateNode(line, outer.x, outer.y, anim));
        if (cut.chroma) { ghostA.push(plateNode(line, outer.x, outer.y, anim, p.ghostA)); ghostB.push(plateNode(line, outer.x, outer.y, anim, p.ghostB)); }
        continue;
      }
      const emph = Boolean(line.emphasis) && !block;
      const run: string[] = [], runA: string[] = [], runB: string[] = [];
      const ox = emph ? line.x : outer.x, oy = emph ? line.y : outer.y;
      const baseY = line.offset ? line.y + line.offset.y : line.y;
      for (const { g, x } of positions(line)) {
        const k = order++;
        let value = enter(k, line.size, false);
        let ink = paintClasses(undefined, line.color);
        if (emph && line.paint) {
          const paint = line.paint, clear = (c: string) => withAlpha(c, 0);
          const extra = paint.gradient
            ? (ink = paintClasses({ gradient: { ...paint.gradient, from: p.ink, to: p.ink } }, p.ink), film.track([[0, { gradFrom: p.ink, gradTo: p.ink }], [1, { gradFrom: paint.gradient.from, gradTo: paint.gradient.to }]], 320, punchAt, EASE.soft, { step: 0 }))
            : paint.stroke
              ? (ink = paintClasses({ stroke: { ...paint.stroke, hollow: false, color: clear(paint.stroke.color) } }, p.ink), film.track([[0, { color: p.ink, textStrokeColor: clear(paint.stroke.color) }], [1, { color: paint.stroke.hollow ? clear(p.ink) : line.color, textStrokeColor: paint.stroke.color }]], 320, punchAt, EASE.soft, { step: 0 }))
              : "";
          if (extra) value = value ? `${value}, ${extra}` : extra;
        } else if (emph) {
          ink = paintClasses(undefined, p.ink);
          const extra = film.track([[0, { color: p.ink }], [1, { color: line.color }]], 260, punchAt, EASE.soft, { step: 0 });
          value = value ? `${value}, ${extra}` : extra;
        } else if (line.paint) ink = paintClasses(line.paint, line.color);
        const anim = film.use(value ? [value] : []);
        if (typing && !line.offset) cursorStops.push({ t: S + k * typeStep, left: x - outer.x, x: x + measure.width(g, line.size, line.bold, line.face) - outer.x, y: line.y - outer.y, h: line.size });
        run.push(glyphNode(g, x - ox, baseY - oy, line, ink, anim));
        if (cut.chroma) {
          runA.push(glyphNode(g, x - outer.x, baseY - outer.y, line, `text-[${p.ghostA}]`, anim));
          runB.push(glyphNode(g, x - outer.x, baseY - outer.y, line, `text-[${p.ghostB}]`, anim));
        }
      }
      ghostA.push(...runA); ghostB.push(...runB);
      if (emph) {
        const r = { x: line.x - outer.x, y: line.y - outer.y, width: line.width, height: line.height };
        const lift = Math.round(line.size * 0.2);
        const punch = film.track([[0, { translateY: 0 }], [0.35, { translateY: -lift }], [0.68, { translateY: lift * 0.15 }], [1, { translateY: 0 }]], V.punchMs, punchAt, EASE.out);
        const glow = line.paint?.glow;
        const lit = glow ? [film.track([[0, { dropShadowColor: withAlpha(glow.color, 0) }], [1, { dropShadowColor: glow.color }]], 420, punchAt, EASE.soft, { step: 0 })] : [];
        const glowClass = glow ? ` glow-[${glow.radius}px] glow-[${withAlpha(glow.color, 0)}]${glow.gain !== 1 ? ` glow-gain-[${glow.gain}]` : ""}` : "";
        main.push(view(r, `${glowClass}${film.use([punch, ...lit])}`, run));
      } else main.push(...run);
    }
    // Typewriter: a caret that follows the typing, then blinks.
    if (typing && cursorStops.length) {
      const first = cursorStops[0]!, lastStop = cursorStops.at(-1)!, span = Math.max(34, lastStop.t - first.t);
      const thickness = Math.max(3, Math.round(style.motion.cursor.thickness * W / 1080));
      const stops: [number, Props][] = [[0, { translateX: first.left, translateY: first.y }]];
      for (const stop of cursorStops) { const q = (stop.t - first.t) / span; if (q > 0 && q < 1) stops.push([q, { translateX: stop.x, translateY: stop.y }]); }
      stops.push([1, { translateX: lastStop.x, translateY: lastStop.y }]);
      const caret = `<View class="absolute left-[0px] top-[${px(Math.round(first.h * 0.12))}] w-[${thickness}px] h-[${px(Math.round(first.h * 1.02))}] bg-[${p.accent}]${film.use([
        film.track(stops, span, first.t, EASE.linear, { step: 0 }),
        film.track([[0, { opacity: 1 }], [0.48, { opacity: 1 }], [0.5, { opacity: 0 }], [0.98, { opacity: 0 }], [1, { opacity: 1 }]], 900, lastStop.t + 300, EASE.linear, { iterations: 0, step: 0 })])}" />`;
      main.push(caret);
    }
    // The block: a wipe (a moving window over still type) or slices sliding in from alternate sides.
    const local = { x: 0, y: 0, width: outer.width, height: outer.height };
    let content: string[];
    if (entrance === "wipe") {
      const w = outer.width + 8;
      const win = film.track([[0, { translateX: -w }], [1, { translateX: 0 }]], 520, S, EASE.inOut);
      const counter = film.track([[0, { translateX: w }], [1, { translateX: 0 }]], 520, S, EASE.inOut);
      const bar = Math.max(6, Math.round(size * 0.07));
      const edge = `<View class="absolute left-[${px(-bar)}] top-[0px] w-[${bar}px] h-[${px(outer.height)}] bg-[${p.accent}]${film.use([film.track([[0, { translateX: 0, opacity: 1 }], [0.85, { translateX: w, opacity: 1 }], [1, { translateX: w, opacity: 0 }]], 620, S, EASE.inOut)])}" />`;
      content = [view(local, ` overflow-hidden${film.use([win])}`, [view(local, film.use([counter]), main)]), edge];
    } else if (entrance === "slice") {
      const bands = 3, bh = Math.ceil(outer.height / bands);
      content = [];
      for (let k = 0; k < bands; k++) {
        const from = (k % 2 ? 1 : -1) * (W * 0.9);
        const band = { x: 0, y: k * bh, width: outer.width, height: bh + (k < bands - 1 ? 1 : 0) };
        content.push(view(band, ` overflow-hidden${film.use([film.track([[0, { translateX: from }], [1, { translateX: 0 }]], 460, S + k * 60, EASE.out)])}`,
          [view({ x: 0, y: -k * bh, width: outer.width, height: outer.height }, "", main)]));
      }
    } else content = main;
    // Chromatic ghosts: two tinted passes behind, offset and spiking on the cut and on every beat.
    const ghosts: string[] = [];
    if (cut.chroma && ghostA.length) {
      const o = Math.max(2, size * V.ghosts.offsetEm);
      const blend = light(p.bg) ? "mix-blend-multiply" : "mix-blend-screen";
      const beats = Math.max(1, Math.ceil((holdEnd - S) / program.beatMs));
      for (const [k, list] of [ghostA, ghostB].entries()) {
        const sx = k ? -1 : 1, sy = k ? -0.4 : 0.6;
        const spike = V.ghosts.spike;
        const at = (m: number): Props => ({ translateX: sx * o * m, translateY: sy * o * m });
        const beat = film.track([[0, at(spike)], [0.25, at(1.4)], [1, at(1)]], program.beatMs, S, EASE.out, { iterations: beats });
        const contentGhost = entrance === "wipe" || entrance === "slice" ? [view(local, film.use([film.track([[0, { opacity: 0 }], [0.9, { opacity: 0 }], [1, { opacity: 1 }]], 520, S, EASE.linear)]), list)] : list;
        ghosts.push(view(local, ` ${blend} opacity-${Math.round(V.ghosts.alpha * 20) * 5}${film.use([beat])}`, contentGhost));
      }
    }
    // Hold: the block drifts, floats, breathes or jitters while it stays.
    const holdParts: string[] = [];
    const life = Math.max(400, holdEnd - S);
    switch (cut.motion) {
      case "drift": { const d = size * V.driftEm, side = i % 2 ? -1 : 1; holdParts.push(film.track([[0, { translateX: 0, translateY: 0 }], [1, { translateX: d * side, translateY: -d * 0.5 }]], life, S, EASE.inOut)); break; }
      case "float": { const a = size * 0.07, period = 2400; holdParts.push(film.track([[0, { translateY: 0 }], [0.5, { translateY: -a }], [1, { translateY: 0 }]], period, S, EASE.inOut, { iterations: Math.ceil(life / period) })); break; }
      case "breathe": { const period = 2800; holdParts.push(film.track([[0, { scale: 1 }], [0.5, { scale: 1.035 }], [1, { scale: 1 }]], period, S, EASE.inOut, { iterations: Math.ceil(life / period) })); break; }
      case "jitter": {
        const r = generator(seedOf(`jitter\u0000${i}`)), a = Math.max(2, size * 0.025);
        const stops: [number, Props][] = [];
        for (let j = 0; j < 12; j++) stops.push([j / 12, { translateX: (r() - 0.5) * 2 * a, translateY: (r() - 0.5) * 2 * a }]);
        stops.push([1, stops[0]![1]]);
        holdParts.push(film.track(stops, 1000, S, EASE.linear, { stepped: true, iterations: Math.ceil(life / 1000) }));
        break;
      }
      default:
    }
    const hold = view(local, film.use(holdParts), [...ghosts, ...content]);
    // Exit: only where the transition shows the old cut going (a fade or a wipe); a hard cut replaces it.
    const exitParts: string[] = [];
    if (cut.bang) {
      const a = Math.max(6, Math.round(size / 8));
      exitParts.push(film.track([[0, { translateX: 0 }], [0.12, { translateX: -a }], [0.28, { translateX: a }], [0.44, { translateX: -a * 0.7 }], [0.6, { translateX: a * 0.5 }], [0.78, { translateX: -a * 0.25 }], [1, { translateX: 0 }]], 420, revealEnd - 40, EASE.linear));
    }
    const next = program.cuts[i + 1];
    if (next && (next.transition === "fade" || next.transition.startsWith("wipe-"))) {
      exitParts.push(V.exitEm
        ? film.track([[0, { opacity: 1, translateY: 0 }], [1, { opacity: 0, translateY: -size * V.exitEm }]], V.exitMs, S + cut.hold - V.exitMs * 0.4, EASE.in)
        : film.track([[0, { opacity: 1 }], [1, { opacity: 0 }]], V.exitMs, S + cut.hold - V.exitMs * 0.5, EASE.in));
    }
    // Notes, labels, credit: fade in with the cut.
    const quietNodes: string[] = [];
    for (const index of cut.quiet) {
      const line = layout.lines[index]!;
      const anim = film.use([film.track([[0, { opacity: 0, translateY: line.size * 0.3 }], [1, { opacity: 1, translateY: 0 }]], 480, S + Math.min(window + enterMs, cut.hold * 0.5) * 0.6, EASE.out)]);
      const run = positions(line).map(({ g, x }) => glyphNode(g, x - outer.x, line.y - outer.y, line, paintClasses(undefined, line.color), ""));
      quietNodes.push(view(local, anim, run));
    }
    inner.push(view(outer, film.use(exitParts), [hold, ...quietNodes]));
    for (const s of cut.shapes) if (s.over) inner.push(shapeNode(s));
    // A trailing "!" flashes the screen as the line lands; flash and glitch transitions flash or tear it as the cut comes in.
    if (cut.bang) inner.push(`<View class="absolute left-[0px] top-[0px] w-[${W}px] h-[${H}px] bg-[${variant === "editorial" ? p.accent : p.ink}]${film.use([film.track([[0, { opacity: 0 }], [0.18, { opacity: variant === "editorial" ? 0.22 : 0.55 }], [1, { opacity: 0 }]], 340, revealEnd - 60, EASE.soft)])}" />`);
    if (tr === "flash") inner.push(`<View class="absolute left-[0px] top-[0px] w-[${W}px] h-[${H}px] bg-[${light(p.bg) ? p.accent : "#ffffff"}]${film.use([film.track([[0, { opacity: 0.92 }], [0.3, { opacity: 0.6 }], [1, { opacity: 0 }]], 250, cut.inAt, EASE.linear, { stepped: true })])}" />`);
    if (tr === "glitch") {
      const r = generator(seedOf(`glitch\u0000${i}`));
      for (let k = 0; k < 7; k++) {
        const h = Math.round(H * (0.01 + r() * 0.07)), y = Math.round(r() * (H - h));
        const color = [p.ghostA, p.ghostB, p.ink, p.accent][k % 4]!;
        const dx = (r() - 0.5) * W * 0.3;
        inner.push(`<View class="absolute left-[0px] top-[${y}px] w-[${W}px] h-[${h}px] bg-[${color}]${film.use([film.track([[0, { opacity: 0.9, translateX: dx }], [0.34, { opacity: 0.9, translateX: -dx * 0.6 }], [0.67, { opacity: r() < 0.5 ? 0.9 : 0, translateX: dx * 0.3 }], [1, { opacity: 0, translateX: 0 }]], 250, cut.inAt + k * 12, EASE.linear, { stepped: true })])}" />`);
      }
    }
    // A vignette, lighter on light grounds.
    if (program.texture.vignette) {
      const a = Math.round(program.texture.vignette * (light(p.bg) ? 0.4 : 1) * 255).toString(16).padStart(2, "0");
      inner.push(`<View class="absolute left-[0px] top-[0px] w-[${W}px] h-[${H}px] bg-[radial-gradient(#00000000,#00000000_55%,#000000${a}_100%)]" />`);
    }
    // The signature, in this cut's colour for it.
    for (const line of signature) for (const { g, x } of positions(line)) {
      inner.push(glyphNode(g, x, line.y, line, paintClasses(undefined, cut.signature), i === 0 ? "" : film.use([film.track([[0, { opacity: 0 }], [1, { opacity: 1 }]], Math.max(17, tMs), cut.inAt, EASE.soft, { step: 0 })])));
    }
    // Gates: a cut appears when its transition starts and is hidden once the next one covers it.
    const show = i === 0 ? "" : film.use([film.track([[0, { opacity: 0 }], [1, { opacity: 1 }]], 17, cut.inAt, EASE.linear, { step: 0 })]);
    const hide = last ? "" : film.use([film.track([[0, { opacity: 1 }], [1, { opacity: 0 }]], 17, cut.end, EASE.linear, { step: 0 })]);
    nodes.push(view(full, show, [hide ? view(full, hide, inner) : inner.join("\n")]));
  }
  /* Texture over the picture. */
  const textures: LyricsComposition["textures"][number][] = [];
  const tex = program.texture;
  // Textures are drawn at the canvas's own resolution: the rasteriser skips transparent pixels, but a scaled image has almost none.
  if (tex.paper) { textures.push({ file: "lt_paper.png", kind: "paper", width: W, height: H, alpha: tex.paper }); nodes.push(`<Image class="absolute left-[0px] top-[0px] w-[${W}px] h-[${H}px]" src="lt_paper.png" />`); }
  if (tex.scanlines) { textures.push({ file: "lt_scan.png", kind: "scanlines", width: W, height: H, alpha: tex.scanlines }); nodes.push(`<Image class="absolute left-[0px] top-[0px] w-[${W}px] h-[${H}px]" src="lt_scan.png" />`); }
  if (tex.grain) {
    const pad = Math.min(96, 2048 - Math.max(W, H));
    const gw = W + pad, gh = H + pad;
    textures.push({ file: "lt_grain.png", kind: "grain", width: gw, height: gh, alpha: tex.grain });
    const stops: [number, Props][] = [];
    for (let j = 0; j < 12; j++) stops.push([j / 12, { translateX: -Math.round(random() * pad), translateY: -Math.round(random() * pad) }]);
    stops.push([1, stops[0]![1]]);
    nodes.push(`<Image class="absolute left-[0px] top-[0px] w-[${gw}px] h-[${gh}px]${film.use([film.track(stops, 1000, 0, EASE.linear, { stepped: true, iterations: 0 })])}" src="lt_grain.png" />`);
  }
  const frames = Math.ceil((program.durationMs / 1000) * LYRICS_TIMING.fps) + 1;
  return { body: nodes.join("\n"), keyframes: film.keyframes, animations: film.animations, frames, emojiKeys, plates, textures };
}
