import type { Aspect } from "../dsl.ts";

export const TEMPLATE_IDS = ["text", "document", "quote", "code", "stat", "list", "chat", "table", "comparison"] as const;
export type TemplateId = (typeof TEMPLATE_IDS)[number];
/** Style ids. Every template has classic and editorial; poster exists only where registered (text). */
export const VARIANT_IDS = ["classic", "editorial", "poster"] as const;
export type VariantId = (typeof VARIANT_IDS)[number];
/** Visible graphemes one card may hold (TEMPLATE_LIMITS.maxGraphemes). */
export const TEMPLATE_MAX_GRAPHEMES = 2400;
/** Beyond this the text template hands over to document. */
export const TEXT_MAX_GRAPHEMES = 280;
export const MOTIONS = ["none", "reveal", "typewriter"] as const;
export type TemplateMotion = (typeof MOTIONS)[number];

/** Content is extracted from explicit source syntax, never generated by a model. */
export type DocumentBlock =
  | { readonly kind: "paragraph"; readonly text: string }
  | { readonly kind: "heading"; readonly text: string; readonly level: 1 | 2 | 3 }
  | { readonly kind: "list"; readonly items: readonly string[]; readonly ordered: boolean }
  | { readonly kind: "code"; readonly code: string; readonly language?: string };

export type TemplateContent =
  /** Short prose shown as typography alone: the source paragraphs, nothing added. */
  | { readonly kind: "text"; readonly paragraphs: readonly string[] }
  | { readonly kind: "document"; readonly paragraphs: readonly string[]; readonly blocks?: readonly DocumentBlock[] }
  | { readonly kind: "quote"; readonly text: string; readonly author?: string }
  | { readonly kind: "code"; readonly code: string; readonly language?: string }
  | { readonly kind: "stat"; readonly value: string; readonly label: string }
  | { readonly kind: "list"; readonly items: readonly string[]; readonly ordered: boolean }
  /** `time` is the timestamp line a chat app copied with the message, verbatim. */
  | { readonly kind: "chat"; readonly turns: readonly { readonly speaker: string; readonly text: string; readonly time?: string }[] }
  | { readonly kind: "table"; readonly headers: readonly string[]; readonly rows: readonly (readonly string[])[] }
  | { readonly kind: "comparison"; readonly columns: readonly { readonly title: string; readonly items: readonly string[] }[] };

export interface TemplatePlan {
  readonly version: 1;
  readonly template: TemplateId;
  readonly variant: VariantId;
  readonly motion: TemplateMotion;
  readonly sourceText: string;
  readonly content: TemplateContent;
  readonly aspect: Aspect;
  /** A word or phrase of the source to accent (text template only). It must
   * occur in the content verbatim; anything else is ignored at layout. */
  readonly emphasis?: string;
}

export interface TemplateOverride {
  readonly id?: TemplateId;
  readonly variant?: VariantId;
  readonly motion?: TemplateMotion;
}

export type TemplateDecisionSource = "rules" | "jev" | "fallback" | "override";
export interface TemplateDecision {
  readonly plan: TemplatePlan;
  readonly decisionSource: TemplateDecisionSource;
  readonly availableTemplates: readonly TemplateId[];
  /** Set when the model decider failed; rendering used the local fallback.
   * `kind` is an ERROR_KINDS value such as "provider:auth" or "provider:offline". */
  readonly decisionError?: { readonly kind: string; readonly message: string };
}

export class TemplateInputError extends Error {}
