import type { DiagramDirection, DiagramEdge, DiagramNode } from "./diagram.ts";

export const TEMPLATE_IDS = ["text", "document", "quote", "code", "stat", "list", "chat", "table", "comparison", "diagram", "info", "qr"] as const;
export type TemplateId = (typeof TEMPLATE_IDS)[number];
/** Style ids. Every template has classic and editorial; poster exists only where registered (text). */
export const VARIANT_IDS = ["classic", "editorial", "poster"] as const;
export type VariantId = (typeof VARIANT_IDS)[number];
/** Visible graphemes one card may hold (TEMPLATE_LIMITS.maxGraphemes). */
export const TEMPLATE_MAX_GRAPHEMES = 2400;
/** Beyond this the text template hands over to document. */
export const TEXT_MAX_GRAPHEMES = 280;
export const MOTIONS = ["none", "reveal", "typewriter"] as const;

/** Output frames. "auto" (images only) fits the content: width by content,
 * height hugging it above a per-template minimum. The others are fixed; GIF
 * and MP4 keep them strictly and scroll tall content. */
export const TEMPLATE_ASPECTS = ["auto", "1:1", "4:5", "16:9", "9:16"] as const;
export type TemplateAspect = (typeof TEMPLATE_ASPECTS)[number];
export type FixedAspect = Exclude<TemplateAspect, "auto">;
export const FRAMES: Readonly<Record<FixedAspect, { readonly width: number; readonly height: number }>> = {
  "1:1": { width: 1080, height: 1080 }, "4:5": { width: 1080, height: 1350 },
  "16:9": { width: 1920, height: 1080 }, "9:16": { width: 1080, height: 1920 },
};
/** The legacy card aspects, still accepted as input. */
export const LEGACY_ASPECTS: Readonly<Record<string, FixedAspect>> = { chat: "1:1", doc: "16:9", social: "9:16" };
/** Normalize an aspect for an output: legacy names map to frames; animated
 * outputs never use "auto" (they take 1:1). Undefined when unknown. */
export function templateAspect(value: unknown, output: "image" | "gif" | "video"): TemplateAspect | undefined {
  const raw = typeof value === "string" ? (LEGACY_ASPECTS[value] ?? value) : undefined;
  if (!raw || !(TEMPLATE_ASPECTS as readonly string[]).includes(raw)) return;
  return raw === "auto" && output !== "image" ? "1:1" : raw as TemplateAspect;
}
export const DEFAULT_ASPECT: Readonly<Record<"image" | "gif" | "video", TemplateAspect>> = { image: "auto", gif: "1:1", video: "1:1" };
export type TemplateMotion = (typeof MOTIONS)[number];

/** Content is extracted from explicit source syntax, never generated by a model. */
export type DocumentBlock =
  | { readonly kind: "paragraph"; readonly text: string }
  | { readonly kind: "heading"; readonly text: string; readonly level: 1 | 2 | 3 }
  | { readonly kind: "list"; readonly items: readonly string[]; readonly ordered: boolean }
  | { readonly kind: "code"; readonly code: string; readonly language?: string };

export type TemplateContent =
  /** Short prose shown as typography alone: the source paragraphs, nothing added. */
  | { readonly kind: "text"; readonly paragraphs: readonly string[] }
  | { readonly kind: "document"; readonly paragraphs: readonly string[]; readonly blocks?: readonly DocumentBlock[] }
  | { readonly kind: "quote"; readonly text: string; readonly author?: string }
  | { readonly kind: "code"; readonly code: string; readonly language?: string }
  | { readonly kind: "stat"; readonly value: string; readonly label: string }
  | { readonly kind: "list"; readonly items: readonly string[]; readonly ordered: boolean }
  /** `time` is the timestamp line a chat app copied with the message, verbatim. */
  | { readonly kind: "chat"; readonly turns: readonly { readonly speaker: string; readonly text: string; readonly time?: string }[] }
  | { readonly kind: "table"; readonly headers: readonly string[]; readonly rows: readonly (readonly string[])[] }
  | { readonly kind: "comparison"; readonly columns: readonly { readonly title: string; readonly items: readonly string[] }[] }
  /** A Mermaid flowchart or plain arrow chains: labels verbatim from the source. */
  | { readonly kind: "diagram"; readonly direction: DiagramDirection; readonly nodes: readonly DiagramNode[]; readonly edges: readonly DiagramEdge[] }
  /** Labelled fields (contact details, an account, a server): the optional
   * title line, then each field's label and value verbatim; `type` only picks
   * the styling (phone digits grouped visually, secrets in a pill). */
  | { readonly kind: "info"; readonly title?: string; readonly fields: readonly InfoField[] }
  /** Any text as a QR code: `data` is encoded byte for byte (UTF-8). Never
   * chosen automatically; only the paste-qr action or an explicit override. */
  | { readonly kind: "qr"; readonly data: string; readonly caption?: boolean };

export const INFO_FIELD_TYPES = ["phone", "email", "url", "secret", "plain"] as const;
export type InfoFieldType = (typeof INFO_FIELD_TYPES)[number];
export interface InfoField { readonly label?: string; readonly value: string; readonly type: InfoFieldType }

/** The card typeface: Maple Mono (Peesuto Code, the default) or Noto Sans SC. Code cards are always Maple Mono. */
export const TEMPLATE_FONTS = ["maple", "noto"] as const;
export type TemplateFontChoice = (typeof TEMPLATE_FONTS)[number];
export const DEFAULT_TEMPLATE_FONT: TemplateFontChoice = "maple";

export interface TemplatePlan {
  readonly version: 1;
  readonly template: TemplateId;
  readonly variant: VariantId;
  readonly motion: TemplateMotion;
  readonly sourceText: string;
  readonly content: TemplateContent;
  readonly aspect: TemplateAspect;
  /** A word or phrase of the source to accent (text template only). It must
   * occur in the content verbatim; anything else is ignored at layout. */
  readonly emphasis?: string;
  /** The card typeface; absent means DEFAULT_TEMPLATE_FONT. */
  readonly font?: TemplateFontChoice;
}

export interface TemplateOverride {
  readonly id?: TemplateId;
  readonly variant?: VariantId;
  readonly motion?: TemplateMotion;
}

export type TemplateDecisionSource = "rules" | "jev" | "fallback" | "override";
export interface TemplateDecision {
  readonly plan: TemplatePlan;
  readonly decisionSource: TemplateDecisionSource;
  readonly availableTemplates: readonly TemplateId[];
  /** Set when the model decider failed; rendering used the local fallback.
   * `kind` is an ERROR_KINDS value such as "provider:auth" or "provider:offline". */
  readonly decisionError?: { readonly kind: string; readonly message: string };
}

export class TemplateInputError extends Error {}
