import type { DiagramDirection, DiagramEdge, DiagramNode } from "./diagram.ts";

export const TEMPLATE_IDS = ["text", "document", "quote", "code", "stat", "list", "chat", "table", "comparison", "diagram", "info", "changelog", "terminal", "diff", "error", "timeline", "stats", "lyrics", "qr"] as const;
export type TemplateId = (typeof TEMPLATE_IDS)[number];
/** Style ids. Every template has classic and editorial; poster exists only where registered (text). */
export const VARIANT_IDS = ["classic", "editorial", "poster"] as const;
export type VariantId = (typeof VARIANT_IDS)[number];
/** Visible graphemes one card may hold (TEMPLATE_LIMITS.maxGraphemes). */
export const TEMPLATE_MAX_GRAPHEMES = 2400;
/** The phone readability floor. Cards are mostly looked at on a phone, where
 * any card is shown about `phoneWidth` px wide whatever its canvas, so a font
 * size's effective size is size × phoneWidth / canvas width. Body text never
 * goes below `body` effective px (Apple's footnote size, 13 pt; ljg-card's
 * 40 px on 1080 is 14.4) and labels, times, captions and line numbers never
 * below `secondary` (11 pt, the smallest size in Apple's type scale). On a
 * 1080 canvas that is 36 px body and 32 px secondary, on 1440 48 and 44, on
 * 1920 64 and 56. `referenceWidth` is the width the style tables are drawn
 * for; wider canvases scale them by width / referenceWidth. */
export const READABILITY = { phoneWidth: 390, referenceWidth: 1080, body: 13, secondary: 11 } as const;
/** Beyond this the text template hands over to document. */
export const TEXT_MAX_GRAPHEMES = 280;
export const MOTIONS = ["none", "reveal", "typewriter"] as const;

/** Output frames. "auto" (images only) fits the content: width by content,
 * height hugging it above a per-template minimum. The others are fixed; GIF
 * and MP4 keep them strictly and scroll tall content. */
export const TEMPLATE_ASPECTS = ["auto", "1:1", "4:5", "16:9", "9:16"] as const;
export type TemplateAspect = (typeof TEMPLATE_ASPECTS)[number];
export type FixedAspect = Exclude<TemplateAspect, "auto">;
export const FRAMES: Readonly<Record<FixedAspect, { readonly width: number; readonly height: number }>> = {
  "1:1": { width: 1080, height: 1080 }, "4:5": { width: 1080, height: 1350 },
  "16:9": { width: 1920, height: 1080 }, "9:16": { width: 1080, height: 1920 },
};
/** The legacy card aspects, still accepted as input. */
export const LEGACY_ASPECTS: Readonly<Record<string, FixedAspect>> = { chat: "1:1", doc: "16:9", social: "9:16" };
/** Normalize an aspect for an output: legacy names map to frames; animated
 * outputs never use "auto" (they take 1:1). Undefined when unknown. */
export function templateAspect(value: unknown, output: "image" | "gif" | "video"): TemplateAspect | undefined {
  const raw = typeof value === "string" ? (LEGACY_ASPECTS[value] ?? value) : undefined;
  if (!raw || !(TEMPLATE_ASPECTS as readonly string[]).includes(raw)) return;
  return raw === "auto" && output !== "image" ? "1:1" : raw as TemplateAspect;
}
export const DEFAULT_ASPECT: Readonly<Record<"image" | "gif" | "video", TemplateAspect>> = { image: "auto", gif: "1:1", video: "1:1" };
export type TemplateMotion = (typeof MOTIONS)[number];

/** Content is extracted from explicit source syntax, never generated by a model. */
export type DocumentBlock =
  | { readonly kind: "paragraph"; readonly text: string }
  | { readonly kind: "heading"; readonly text: string; readonly level: 1 | 2 | 3 }
  | { readonly kind: "list"; readonly items: readonly string[]; readonly ordered: boolean }
  | { readonly kind: "code"; readonly code: string; readonly language?: string };

export type TemplateContent =
  /** Short prose shown as typography alone: the source paragraphs, nothing added. */
  | { readonly kind: "text"; readonly paragraphs: readonly string[] }
  | { readonly kind: "document"; readonly paragraphs: readonly string[]; readonly blocks?: readonly DocumentBlock[] }
  | { readonly kind: "quote"; readonly text: string; readonly author?: string }
  | { readonly kind: "code"; readonly code: string; readonly language?: string }
  | { readonly kind: "stat"; readonly value: string; readonly label: string }
  | { readonly kind: "list"; readonly items: readonly string[]; readonly ordered: boolean }
  /** `time` is the timestamp line a chat app copied with the message, verbatim. */
  | { readonly kind: "chat"; readonly turns: readonly { readonly speaker: string; readonly text: string; readonly time?: string }[] }
  | { readonly kind: "table"; readonly headers: readonly string[]; readonly rows: readonly (readonly string[])[] }
  | { readonly kind: "comparison"; readonly columns: readonly { readonly title: string; readonly items: readonly string[] }[] }
  /** A Mermaid flowchart or plain arrow chains: labels verbatim from the source. */
  | { readonly kind: "diagram"; readonly direction: DiagramDirection; readonly nodes: readonly DiagramNode[]; readonly edges: readonly DiagramEdge[] }
  /** Labelled fields (contact details, an account, a server): the optional
   * title line, then each field's label and value verbatim; `type` only picks
   * the styling (phone digits grouped visually, secrets in a pill). */
  | { readonly kind: "info"; readonly title?: string; readonly fields: readonly InfoField[] }
  /** Release notes: an optional title heading, then releases, each a
   * version-like heading (version and date as written, heading markers and
   * separators dropped as syntax) with its sections and bullet items. Section
   * titles are the source's own ("Added", "修复"); `type` only picks a colour. */
  | { readonly kind: "changelog"; readonly title?: string; readonly releases: readonly ChangelogRelease[] }
  /** A shell session: prompt lines (the prompt and the command as written)
   * and the output under them, every line verbatim. `error` and `warning`
   * only pick a colour; `exit` is a final exit-status line. */
  | { readonly kind: "terminal"; readonly lines: readonly TerminalLine[] }
  /** A unified diff: per file the path (from its `+++`/`---` or `diff --git`
   * header, whose lines are syntax and not drawn, like the `a/` `b/` prefixes),
   * mode/rename/binary lines kept verbatim as `meta`, then hunks: the `@@`
   * header and every line as written, its first character the +/-/space. */
  | { readonly kind: "diff"; readonly files: readonly DiffFile[] }
  /** An error with its stack trace: the heading (a `lead` such as
   * `Exception in thread "main"`, the error `type`, the `message`; the colon
   * between type and message is syntax), then the trace lines verbatim in
   * source order: frames, the source lines under Python frames (`code`) and
   * other lines (`note`). `own` marks the reader's own code (not a
   * dependency, the standard library or the runtime), for emphasis only. */
  | { readonly kind: "error"; readonly lead?: string; readonly type?: string; readonly message?: string; readonly trace: readonly ErrorTraceLine[] }
  /** A schedule or milestones: an optional title line, then events, each a
   * time or date as written and its text (a list marker and the separator
   * between them are syntax). */
  | { readonly kind: "timeline"; readonly title?: string; readonly events: readonly { readonly time: string; readonly text: string }[] }
  /** Several metrics: an optional title line, then `label: value` lines,
   * the value a number as written (currency, units, %) and an optional
   * signed change (`+8%`, `↓2`); parentheses around the change and the colon
   * are syntax. The change's sign only picks its colour. */
  | { readonly kind: "stats"; readonly title?: string; readonly metrics: readonly StatsMetric[] }
  /** Song lyrics or a poem: an optional title and credit (an LRC `[ti:]` and
   * `[ar:]` tag, a Markdown `# ` title, or a poem's title and author lines),
   * then stanzas of lines. Lyric markup is syntax and not drawn: `/` cut marks,
   * `*` around an emphasised word, `|` before a note, LRC timestamps. `poem`
   * marks classical verse (equal phrases of four to seven Han characters). */
  | { readonly kind: "lyrics"; readonly title?: string; readonly credit?: string; readonly poem?: boolean; readonly stanzas: readonly LyricStanza[] }
  /** Any text as a QR code: `data` is encoded byte for byte (UTF-8). Never
   * chosen automatically; only the paste-qr action or an explicit override. */
  | { readonly kind: "qr"; readonly data: string; readonly caption?: boolean };

export const INFO_FIELD_TYPES = ["phone", "email", "url", "address", "secret", "plain"] as const;
export type InfoFieldType = (typeof INFO_FIELD_TYPES)[number];
export interface InfoField { readonly label?: string; readonly value: string; readonly type: InfoFieldType }

/** What a changelog section's title says it holds; styling only. */
export const CHANGE_TYPES = ["added", "changed", "fixed", "removed", "security", "other"] as const;
export type ChangeType = (typeof CHANGE_TYPES)[number];
export interface ChangelogSection { readonly title?: string; readonly type: ChangeType; readonly items: readonly string[] }
export interface ChangelogRelease { readonly version: string; readonly date?: string; readonly sections: readonly ChangelogSection[] }

export type TerminalLine =
  | { readonly kind: "prompt"; readonly prompt: string; readonly command: string }
  | { readonly kind: "output"; readonly text: string; readonly tone?: "error" | "warning" }
  | { readonly kind: "exit"; readonly text: string; readonly ok: boolean };

export interface DiffLine { readonly type: "add" | "del" | "context" | "note"; readonly text: string }
export interface DiffHunk { readonly header: string; readonly lines: readonly DiffLine[] }
export interface DiffFile { readonly path?: string; readonly oldPath?: string; readonly meta: readonly string[]; readonly hunks: readonly DiffHunk[] }

export interface ErrorTraceLine { readonly text: string; readonly role: "frame" | "code" | "note"; readonly own: boolean }

/** One lyric line as drawn (markup removed). `breaks` are grapheme offsets
 * where a `/` started a new cut; `emphasis` grapheme ranges [start, end) that
 * were `*marked*`; `note` the text after `|`; `at` and `until` the LRC times
 * in ms (`until` is the next timestamp). A trailing `!` stays text and adds a
 * flash. */
export interface LyricLine {
  readonly text: string;
  readonly breaks?: readonly number[];
  readonly emphasis?: readonly (readonly [number, number])[];
  readonly note?: string;
  readonly at?: number;
  readonly until?: number;
}
/** A stanza: lines between blank lines, with an optional section label (`[Chorus]`). */
export interface LyricStanza { readonly label?: string; readonly lines: readonly LyricLine[] }

export interface StatsMetric { readonly label: string; readonly value: string; readonly delta?: string }

/** The card typeface: Maple Mono (Peesuto Code, the default) or Noto Sans SC. Code cards are always Maple Mono. */
export const TEMPLATE_FONTS = ["maple", "noto"] as const;
export type TemplateFontChoice = (typeof TEMPLATE_FONTS)[number];
export const DEFAULT_TEMPLATE_FONT: TemplateFontChoice = "maple";

export interface TemplatePlan {
  readonly version: 1;
  readonly template: TemplateId;
  readonly variant: VariantId;
  readonly motion: TemplateMotion;
  readonly sourceText: string;
  readonly content: TemplateContent;
  readonly aspect: TemplateAspect;
  /** A word or phrase of the source to accent (text template only). It must
   * occur in the content verbatim; anything else is ignored at layout. */
  readonly emphasis?: string;
  /** The card typeface; absent means DEFAULT_TEMPLATE_FONT. */
  readonly font?: TemplateFontChoice;
  /** The user's signature, drawn small at the foot of every card but QR. Not
   * source text: exempt from the source-fidelity rules. Normalized by
   * templateSignature(); dropped silently when the card font cannot draw it. */
  readonly signature?: string;
}

/** Longest signature, in graphemes (the settings field enforces it too). */
export const SIGNATURE_MAX_GRAPHEMES = 40;
/** A signature as it is drawn: one line (whitespace runs become one space),
 * trimmed, at most SIGNATURE_MAX_GRAPHEMES; undefined when empty or not a string. */
export function templateSignature(value: unknown): string | undefined {
  if (typeof value !== "string") return;
  const line = value.replace(/[\p{Cc}\p{Cf}]/gu, (c) => (c === "\u200d" || /\s/u.test(c) ? c : "")).replace(/\s+/gu, " ").trim();
  if (!line) return;
  const glyphs = [...new Intl.Segmenter(undefined, { granularity: "grapheme" }).segment(line)].map((part) => part.segment);
  return glyphs.slice(0, SIGNATURE_MAX_GRAPHEMES).join("").trim();
}

export interface TemplateOverride {
  readonly id?: TemplateId;
  readonly variant?: VariantId;
  readonly motion?: TemplateMotion;
}

export type TemplateDecisionSource = "rules" | "jev" | "fallback" | "override";
export interface TemplateDecision {
  readonly plan: TemplatePlan;
  readonly decisionSource: TemplateDecisionSource;
  readonly availableTemplates: readonly TemplateId[];
  /** Set when the model decider failed; rendering used the local fallback.
   * `kind` is an ERROR_KINDS value such as "provider:auth" or "provider:offline". */
  readonly decisionError?: { readonly kind: string; readonly message: string };
}

export class TemplateInputError extends Error {}
