// Generated from the tr(english, chinese) call sites; edit freely, keep keys identical
// to the English text. LocalizationTests fails on a missing or unused key.

/// Japanese UI text keyed by the English string (see `Localizer`).
public enum JapaneseStrings {
    public static let table: [String: String] = [
        "History is locked or unavailable. Your existing data has been preserved.": "履歴がロックされているか、読み込めません。既存のデータはそのまま保持されています。",
        "History is locked: its key is missing or does not match. New copies are kept for this session only. Use Start fresh to begin a new history; the old one is kept aside.": "履歴がロックされています。鍵が見つからないか一致しません。新しくコピーした内容はこのセッションの間だけ保持されます。「新しく始める」で新しい履歴を作成できます（古い履歴は別に保管されます）。",
        "Could not save clipboard history.": "クリップボードの履歴を保存できませんでした。",
        "Could not save this image.": "この画像を保存できませんでした。",
        "Could not save these files.": "これらのファイルを履歴に保存できませんでした。",
        "Start a new history?": "履歴を新しく始めますか？",
        "The locked history is moved into a dated folder in the app's data folder, not deleted. A new key is created, and copies from this session are kept.": "ロックされた履歴は削除されず、App のデータフォルダ内の日付付きフォルダに移動されます。新しい鍵が作成され、このセッションでコピーした内容は引き継がれます。",
        "Start fresh": "新しく始める",
        "Cancel": "キャンセル",
        "Started a new history. The old one was kept in the app data folder.": "新しい履歴を開始しました。古い履歴は App のデータフォルダに保管されています。",
        "Could not start a new history. Nothing was deleted.": "新しい履歴を開始できませんでした。データは削除されていません。",
        "Clear all history?": "すべての履歴を消去しますか？",
        "All items, including pinned items and images, are permanently removed from this Mac.": "ピン留めした項目や画像を含むすべての項目が、この Mac から完全に削除されます。",
        "Clear history": "履歴を消去",
        "History cleared": "履歴を消去しました",
        "Could not clear history.": "履歴を消去できませんでした。",
        "The action took too long and was stopped.": "処理に時間がかかりすぎたため、停止しました。",
        "Core stopped before the action finished.": "処理が終わる前にコアが停止しました。",
        "Core: ": "コア：",
        "Could not read history. No data was removed.": "履歴を読み込めませんでした。データは削除されていません。",
        "Recommendations are off in secure fields.": "パスワード入力欄ではおすすめを表示しません。",
        "Actions are unavailable. History is still ready.": "アクションは現在使用できません。履歴はそのまま使えます。",
        "Smart paste": "スマートペースト",
        "Create image": "画像を作成",
        "Create GIF": "GIF を作成",
        "Create video": "ビデオを作成",
        "Paste as QR code": "QR コードとしてペースト",
        "Translate to English": "英語に翻訳",
        "Summarize": "要約",
        "Could not read the image on the clipboard.": "クリップボードの画像を読み込めませんでした。",
        "Copy an image or some text first. Protected clipboard content is excluded.": "先に画像かテキストをコピーしてください。保護されたクリップボードの内容は使用しません。",
        "Copy some text first. Protected clipboard content is excluded.": "先にテキストをコピーしてください。保護されたクリップボードの内容は使用しません。",
        "Pin to screen": "画面にピン留め",
        "Create QR code": "QR コードを作成",
        "Typewriter": "タイプライター",
        "Reveal": "順に表示",
        "Still": "静止",
        "Auto": "自動",
        "Preparing…": "準備中…",
        "Accepted…": "受け付けました…",
        "Finishing…": "仕上げ中…",
        "Created. Could not remember this style.": "作成しました。ただし、このスタイルを記憶できませんでした。",
        "Pinned to screen": "画面にピン留めしました",
        "Cancelled": "キャンセルしました",
        "Video needs ffmpeg. Install it with Homebrew (brew install ffmpeg), then retry.": "ビデオには ffmpeg が必要です。Homebrew でインストール（brew install ffmpeg）してから、もう一度お試しください。",
        "Rendering took too long and was stopped. Try a shorter excerpt or a still image.": "レンダリングに時間がかかりすぎたため、停止しました。内容を短くするか、静止画でお試しください。",
        "The action could not finish. Check the AI settings or try again.": "処理を完了できませんでした。AI の設定を確認するか、もう一度お試しください。",
        "Could not read the rendered image. Open the result to try again.": "作成した画像を読み込めませんでした。結果を開いてもう一度お試しください。",
        "Pasted": "ペーストしました",
        "Copied. Allow Accessibility so Peesuto can paste for you; for now, press ⌘V.": "コピーしました。アクセシビリティを許可すると Peesuto が代わりにペーストします。今回は ⌘V を押してください。",
        "Copied only: a password field is active, so Peesuto does not type into it. Press ⌘V yourself if you mean to.": "コピーのみ：パスワード入力中のため、Peesuto は入力しません。ペーストする場合はご自身で ⌘V を押してください。",
        "Copied. Switch to the app you want and press ⌘V.": "コピーしました。目的の App に切り替えて ⌘V を押してください。",
        "Could not paste. Open the result to copy or paste it.": "ペーストできませんでした。結果を開いてコピーまたはペーストしてください。",
        "Could not pin this result.": "この結果を画面にピン留めできませんでした。",
        "Already on in System Settings? Remove Peesuto from the list with −, then add it again.": "システム設定でオンなのに効かない場合は、リストから「−」で Peesuto を削除し、もう一度追加してください。",
        "Copied": "コピーしました",
        "Could not copy this item.": "この項目をコピーできませんでした。",
        "Copied. Press ⌘V in the destination app.": "コピーしました。ペースト先の App で ⌘V を押してください。",
        "Could not save the result.": "結果を保存できませんでした。",
        "Could not update this item.": "この項目を更新できませんでした。",
        "Could not delete this item.": "この項目を削除できませんでした。",
        "Could not save settings.": "設定を保存できませんでした。",
        "Cancelling…": "キャンセル中…",
        "Could not apply history retention.": "履歴の保存期間を適用できませんでした。",
        "Some shortcuts are unavailable. Check Settings → Shortcuts.": "一部のショートカットを使用できません。「設定 → ショートカット」を確認してください。",
        "Welcome to Peesuto": "Peesuto へようこそ",
        "Paste as…": "形式を選んでペースト…",
        "Clipboard History": "クリップボード履歴",
        "Paste Directly": "直接ペースト",
        "Settings…": "設定…",
        "Check for Updates…": "アップデートを確認…",
        "Resume history": "履歴の記録を再開",
        "Pause history": "履歴の記録を一時停止",
        "Quit Peesuto": "Peesuto を終了",
        "Cut": "カット",
        "Copy": "コピー",
        "Paste": "ペースト",
        "Select All": "すべてを選択",
        "Settings": "設定",
        "Could not restore all shortcuts. Check settings.": "一部のショートカットを元に戻せませんでした。設定を確認してください。",
        "Peesuto is already running": "Peesuto はすでに起動しています",
        "Quit the other version before opening this build. Both cannot use the same history at once.": "このビルドを開く前に、もう一方のバージョンを終了してください。同じ履歴を同時に使うことはできません。",
        "Paste as": "形式を選んでペースト",
        "Preparing the card": "カードを準備中",
        "An image is on the clipboard: pin it, or copy text to make a card.": "クリップボードには画像があります。画面にピン留めできます。カードを作るにはテキストをコピーしてください。",
        "Copy some text first. Protected clipboard content is not used.": "先にテキストをコピーしてください。保護されたクリップボードの内容は使用しません。",
        "Accessibility is off, so the result is copied; press ⌘V to paste it.": "アクセシビリティがオフのため、結果はコピーのみ行います。⌘V でペーストしてください。",
        "Image": "画像",
        "Video": "ビデオ",
        "QR code": "QR コード",
        "Clipboard history": "クリップボード履歴",
        "Back": "戻る",
        "Done": "完了",
        "Continue": "続ける",
        "Copy text, paste a card": "テキストをコピーして、カードでペースト",
        "Peesuto keeps your clipboard history.\nOne shortcut, then one key, turns what you copied into an image, GIF or video.": "Peesuto はクリップボードの履歴を保存します。\nショートカットとキーひとつで、コピーした内容が画像、GIF、ビデオになります。",
        "Off": "オフ",
        "Let Peesuto paste for you": "ペーストを Peesuto に任せる",
        "Accessibility access lets Peesuto press ⌘V in the app you’re using.\nWithout it, shortcuts only copy the result.": "アクセシビリティを許可すると、使用中の App で Peesuto が ⌘V を押せます。\n許可しない場合、ショートカットは結果をコピーするだけです。",
        "Accessibility": "アクセシビリティ",
        "Allowed": "許可済み",
        "Open System Settings": "システム設定を開く",
        "Your history is encrypted and stays on this Mac.\nmacOS may ask once about Peesuto’s Keychain item; choose Always Allow.": "履歴は暗号化され、この Mac の外には出ません。\nPeesuto のキーチェーン項目について macOS が一度確認することがあります。「常に許可」を選んでください。",
        "You’re all set": "準備ができました",
        "Copy some text, click where it should go, press the shortcut and pick a format.": "テキストをコピーし、ペースト先をクリックしてから、ショートカットで形式を選びます。",
        "Open clipboard history": "クリップボード履歴を開く",
        "Smarter suggestions (optional)": "より賢いおすすめ（オプション）",
        "Connect your own AI key. Everything works without it.": "ご自身の AI キーを接続。なくてもすべて使えます。",
        "Set Up…": "設定する…",
        "All shortcuts and preferences are in Settings": "すべてのショートカットと環境設定は「設定」にあります",
        "Search your clipboard": "クリップボードを検索",
        "Pinned: stays open when you click elsewhere": "固定中：ほかの場所をクリックしても閉じません",
        "Keep the panel open when you click elsewhere": "ほかの場所をクリックしてもパネルを閉じない",
        "Keep panel open": "パネルを固定",
        "RECENT": "最近の項目",
        "PREVIEW": "プレビュー",
        "Copy something to begin": "何かをコピーするとここに表示されます",
        "No matches": "一致する項目はありません",
        "Pin / unpin": "ピン留め / 解除",
        "Delete": "削除",
        "Save result": "結果を保存",
        "A little space for everything you copy.": "コピーしたすべてに、ちょっとした居場所を。",
        "Suggested": "おすすめ",
        "Start fresh…": "新しく始める…",
        "Actions": "アクション",
        "Keep this image floating on screen": "この画像を画面上に浮かべておく",
        "Template": "テンプレート",
        "Style": "スタイル",
        "Change style": "スタイルを変更",
        "Motion": "モーション",
        "Frame for this result (the default is in Settings → Shortcuts)": "この結果の縦横比（デフォルトは「設定 → ショートカット」）",
        "Output format": "出力形式",
        "Preview · sample history": "プレビュー版 · サンプル履歴",
        "History paused": "履歴の記録を一時停止中",
        "Stored on this Mac": "この Mac に保存",
        "Navigate": "移動",
        "Close": "閉じる",
        "Clipboard": "クリップボード",
        "Precomposed": "事前生成済み",
        "Rendered in the background right after you copied it.": "コピーした直後にバックグラウンドで作成されました。",
        "Could not save the image.": "画像を保存できませんでした。",
        "Copy image": "画像をコピー",
        "Save as…": "別名で保存…",
        "Close all pins": "すべてのピンを閉じる",
        "Fix the highlighted rule before saving.": "保存する前に、強調表示されたルールを修正してください。",
        "At most 100 custom rules.": "カスタムルールは 100 件までです。",
        "Saved. Applies when the current task finishes.": "保存しました。現在の処理が終わると適用されます。",
        "Saved": "保存しました",
        "Not saved: Core rejected a rule.": "保存されていません：コアがルールを拒否しました。",
        "Not saved: ": "保存されていません：",
        "Saved. Core is not reachable right now; settings apply when it starts.": "保存しました。現在コアに接続できないため、コアの起動時に適用されます。",
        "Wait for the current task to finish.": "現在の処理が終わるまでお待ちください。",
        "Core is not reachable.": "コアに接続できません。",
        "Enter what to match.": "照合する内容を入力してください。",
        "The pattern is longer than 500 characters.": "パターンが 500 文字を超えています。",
        "The replacement is longer than 100 characters.": "置換文字列が 100 文字を超えています。",
        "This is not a valid regular expression.": "正しい正規表現ではありません。",
        "Precompose": "事前生成",
        "Renders each copied text in the background so Paste as… and the paste shortcuts return at once. Uses extra CPU and battery; pauses in Low Power Mode and when the Mac is hot.": "コピーしたテキストをバックグラウンドで作成しておき、「形式を選んでペースト…」やペーストのショートカットですぐに使えるようにします。CPU とバッテリーを余分に使います。低電力モードのときや Mac が高温のときは一時停止します。",
        "Precompose also uses the AI model": "事前生成でも AI モデルを使用",
        "Every text you copy is then sent to the model, processed as set in “Content sent to the AI model” below.": "オンにすると、コピーしたすべてのテキストが、下の「AI モデルに送信する内容」の設定に従って処理されてからモデルに送信されます。",
        "Off: local rules choose the template for precompose.": "オフ：事前生成のテンプレートはローカルルールで選びます。",
        "Don’t precompose text that contains a secret": "秘密情報を含むテキストは事前生成しない",
        "Content sent to the AI model": "AI モデルに送信する内容",
        "Original text": "原文",
        "Redact sensitive info": "機密情報を伏せる",
        "Structure only": "構造のみ",
        "The model sees your text as copied.": "モデルはコピーしたテキストをそのまま受け取ります。",
        "Only the shape (lengths, lines, kinds of content) is sent; no words.": "構造（長さ、行数、内容の種類）だけを送信し、文字は送信しません。",
        "Matches of the rules below are replaced before sending.": "送信前に、下のルールに一致した部分を置き換えます。",
        "Applies to every model decision: shortcuts, precompose and smart paste. Local rules never send anything.": "ショートカット、事前生成、スマートペーストなど、モデルによるすべての判断に適用されます。ローカルルールは何も送信しません。",
        "Built-in rules": "組み込みルール",
        "Core is not reachable; showing rule ids with their defaults.": "コアに接続できないため、ルール ID とデフォルトの状態のみ表示しています。",
        "Custom rules": "カスタムルール",
        "Add rule…": "ルールを追加…",
        "Replace your own words, names or patterns before they reach the model.": "独自の語句、名前、パターンを、モデルに届く前に置き換えます。",
        "Edit": "編集",
        "Regex": "正規表現",
        "Keywords": "キーワード",
        "Text": "テキスト",
        "(removed)": "（削除）",
        "also in images": "画像内も置換",
        "Test": "テスト",
        "Uses the saved rules. Save first to test changes.": "保存済みのルールを使います。変更をテストするには先に保存してください。",
        "The model receives": "モデルが受け取る内容",
        "Shown in images": "画像に表示される内容",
        "Contains a secret.": "秘密情報が含まれています。",
        "Edit rule": "ルールを編集",
        "New rule": "新規ルール",
        "Name": "名前",
        "Match": "照合方法",
        "Keywords (one per line)": "キーワード（1 行に 1 つ）",
        "Keywords, one per line": "キーワード（1 行に 1 つ）",
        "Regular expression": "正規表現",
        "Text to match": "照合するテキスト",
        "Replace with": "置換後の文字列",
        "Case sensitive": "大文字と小文字を区別",
        "Whole word": "単語単位",
        "Also replace in images": "画像内でも置換",
        "Off: only what the model sees changes. On: the rendered image, GIF and video show the replacement too.": "オフ：モデルが受け取る内容だけを置き換えます。オン：作成される画像、GIF、ビデオにも置換後の文字列が表示されます。",
        "Changes apply after saving.": "保存すると変更が適用されます。",
        "Native preview": "ネイティブプレビュー版",
        "General": "一般",
        "AI & actions": "AI とアクション",
        "Shortcuts": "ショートカット",
        "Privacy & precompose": "プライバシーと事前生成",
        "Templates": "テンプレート",
        "History & privacy": "履歴とプライバシー",
        "Changes apply immediately": "変更はすぐに適用されます",
        "Save changes": "変更を保存",
        "Language": "言語",
        "Follow system": "システムに合わせる",
        "Suggest relevant history": "関連する履歴をおすすめ",
        "Open at login": "ログイン時に開く",
        "Not available in the preview build.": "プレビュー版では使用できません。",
        "Allow Peesuto in System Settings → Login Items.": "「システム設定 → ログイン項目」で Peesuto を許可してください。",
        "Open Login Items": "ログイン項目を開く",
        "Automatically check for updates": "アップデートを自動的に確認",
        "Current version ": "現在のバージョン ",
        "Updates are off in the preview build.": "プレビュー版ではアップデートを確認しません。",
        "Paste into other apps": "ほかの App へのペースト",
        "Accessibility allows Peesuto to restore focus and paste. Copy works without it.": "アクセシビリティを許可すると、Peesuto が元の App に戻ってペーストできます。許可しなくてもコピーは使えます。",
        "Access granted": "許可されています",
        "Access not granted": "許可されていません",
        "Open permissions": "アクセス権を設定",
        "Core diagnostics": "コアの診断",
        "Refresh": "更新",
        "Recent Core error output, kept in memory only (last 20 lines).": "コアの最近のエラー出力です。メモリ上にのみ保持されます（直近 20 行）。",
        "No messages.": "メッセージはありません。",
        "About Peesuto": "Peesuto について",
        "Version ": "バージョン ",
        "Show welcome guide": "ようこそガイドを表示",
        "Could not change the login item. Check System Settings → Login Items.": "ログイン項目を変更できませんでした。「システム設定 → ログイン項目」を確認してください。",
        "Skip the chooser": "選択画面を省略",
        "Give an output its own key to go straight to it. Off by default; the chooser reaches them all.": "出力形式ごとに専用のキーを割り当てると、選択画面を経ずに直接作成できます。デフォルトではオフで、どれも選択画面から使えます。",
        "Paste as image": "画像としてペースト",
        "Paste as GIF": "GIF としてペースト",
        "Paste as video": "ビデオとしてペースト",
        "Any content can become a QR code, so it never takes part in automatic template choice. Use Q in the chooser, this shortcut, or the result window's template menu.": "どんな内容でも QR コードにできるため、テンプレートの自動選択には含まれません。選択画面の Q、このショートカット、または結果ウインドウのテンプレートメニューを使ってください。",
        "Pins a copied image, or the image card of copied text, in a floating window. Nothing is pasted and the clipboard is left alone.": "コピーした画像（またはコピーしたテキストから作った画像カード）を、フローティングウインドウで画面にピン留めします。ペーストはせず、クリップボードも変更しません。",
        "Click a shortcut and press your keys. Clear it to disable. Changes apply after saving.": "ショートカットをクリックしてキーを押します。消去すると無効になります。保存すると適用されます。",
        "The result is pasted into the app you were typing in and stays on the clipboard. Without Accessibility, or in a password field, it is only copied. Video requires ffmpeg.": "結果は入力中の App にペーストされ、クリップボードにも残ります。アクセシビリティが許可されていない場合やパスワード入力欄では、コピーのみ行います。ビデオには ffmpeg が必要です。",
        "Preview checks bindings but does not register global shortcuts.": "プレビュー版では割り当ての確認のみ行い、グローバルショートカットは登録しません。",
        "Image frame": "画像の縦横比",
        "GIF frame": "GIF の縦横比",
        "Video frame": "ビデオの縦横比",
        "Images fit their content by default. GIF and video keep a fixed frame and scroll long content.": "画像はデフォルトで内容に合わせたサイズになります。GIF とビデオは縦横比が固定で、長い内容はスクロールして表示します。",
        "Prepare on copy": "コピー時に事前生成",
        "Copying renders in the background with local rules, so Paste as… shows the card and pastes it at once. Pauses in Low Power Mode.": "コピーするとローカルルールでバックグラウンドで作成しておくので、「形式を選んでペースト…」ですぐにカードを表示してペーストできます。低電力モードでは一時停止します。",
        "Disabled": "未設定",
        "Press shortcut…": "キーを押してください…",
        "Disable shortcut": "ショートカットを無効にする",
        "Offline mode": "オフラインモード",
        "Cards and GIFs render locally. Text actions use the provider you choose.": "カードと GIF はこの Mac 上で作成されます。テキストのアクションには選択したプロバイダを使います。",
        "Text generation": "テキスト生成",
        "Not configured": "未設定",
        "OpenAI compatible / Ollama": "OpenAI 互換 / Ollama",
        "Hosted": "ホスティング",
        "Endpoint URL": "エンドポイント URL",
        "Model": "モデル",
        "Model, e.g. anthropic/claude-sonnet-5": "モデル（例：anthropic/claude-sonnet-5）",
        "New key (leave blank to keep existing)": "新しいキー（空欄のままなら現在のキーを保持）",
        "Recommendations & card style": "おすすめとカードのスタイル",
        "Local rules": "ローカルルール",
        "Basic fallback": "基本のフォールバック",
        "Compatible endpoint": "互換エンドポイント",
        "Account ID": "アカウント ID",
        "New token (leave blank to keep existing)": "新しいトークン（空欄のままなら現在のトークンを保持）",
        "Default. Picks templates from the text's structure, offline. Right for most people.": "デフォルト。テキストの構造からテンプレートを選びます。オフラインで動作し、ほとんどの方にはこれで十分です。",
        "No decisions: every card uses the basic layout.": "判断を行いません。すべてのカードに基本のレイアウトを使います。",
        "Experimental. A small model you run yourself on this Mac (see docs/laya.md).": "試験的な機能です。この Mac でご自身が動かす小さなモデルを使います（docs/laya.md を参照）。",
        "Your own endpoint that speaks Jev's protocol.": "Jev のプロトコルに対応した独自のエンドポイント。",
        "The Peesuto hosted service.": "Peesuto のホスティングサービス。",
        "Jev with your own key: smarter suggestions in the history panel and template choices. Text is sent to the service after secrets are redacted.": "ご自身のキーで Jev を使います。履歴パネルのおすすめとテンプレートの選択が賢くなります。テキストは秘密情報を伏せてからサービスに送信されます。",
        "The same key serves Jev and text generation.": "同じキーを Jev とテキスト生成の両方に使います。",
        "Used for Jev only.": "Jev にのみ使います。",
        "Get a key": "キーを取得",
        "Keep history": "履歴の保存期間",
        "7 days": "7 日",
        "30 days": "30 日",
        "90 days": "90 日",
        "Forever": "無期限",
        "Pinned items are kept. History and images are encrypted on this Mac.": "ピン留めした項目は保持されます。履歴と画像はこの Mac 上で暗号化されます。",
        "Excluded apps · one bundle ID per line": "除外する App · 1 行に 1 つのバンドル ID",
        "Password and transient clipboard types are always excluded. Provider credentials stay in Keychain.": "パスワードや一時的なクリップボードの種類は常に除外されます。プロバイダの認証情報はキーチェーンに保存されます。",
        "History is locked. New copies are kept for this session only.": "履歴がロックされています。新しくコピーした内容はこのセッションの間だけ保持されます。",
        "Remove every history item from this Mac.": "この Mac からすべての履歴項目を削除します。",
        "Clear history…": "履歴を消去…",
        "Could not save the frames.": "縦横比を保存できませんでした。",
        "Could not save shortcuts. Check for duplicates or keys used by another app.": "ショートカットを保存できませんでした。重複していないか、ほかの App が使っていないか確認してください。",
        "Saved. AI settings apply when the current task finishes.": "保存しました。AI の設定は現在の処理が終わると適用されます。",
        "Saved. Check your provider configuration before using AI actions.": "保存しました。AI アクションを使う前にプロバイダの設定を確認してください。",
        "Enter an API key for the selected service.": "選択したサービスの API キーを入力してください。",
        "Could not save all changes. Check the shortcut, model and endpoint.": "一部の変更を保存できませんでした。ショートカット、モデル、エンドポイントを確認してください。",
        "Ready": "準備完了",
        "Grant access…": "アクセスを許可…",
        "View result": "結果を表示",
        "Dismiss": "閉じる",
        "Peesuto picks a template from what you copied. Turn one off to keep it out of automatic choice; you can still pick it by hand after a card is made. Click a style to make it the default, click it again to let Peesuto decide.": "Peesuto はコピーした内容に合わせてテンプレートを選びます。オフにしたテンプレートは自動では選ばれませんが、カードを作成したあとに手動で選べます。スタイルをクリックするとデフォルトになり、もう一度クリックすると Peesuto に任せます。",
        "Card font": "カードのフォント",
        "Code cards always use Maple Mono.": "コードのカードには常に Maple Mono を使います。",
        "Noto Sans SC": "Noto Sans SC",
        "Templates are unavailable until Peesuto's engine starts.": "Peesuto のエンジンが起動するまでテンプレートは表示できません。",
        "Loading templates…": "テンプレートを読み込み中…",
        "Restore defaults": "デフォルトに戻す",
        "Signature": "署名",
        "A small line at the foot of every card except QR codes. Leave it empty for none.": "QR コード以外のすべてのカードの下部に入る小さな一行です。空欄にすると表示しません。",
        "Up to 40 characters": "40 文字まで",
        "Only when chosen": "手動で選んだときのみ",
        "Always on (fallback)": "常にオン（フォールバック）",
        "Use automatically": "自動で使用",
        "Default style. Click to let Peesuto decide.": "デフォルトのスタイルです。クリックすると Peesuto に任せます。",
        "Make this the default style": "デフォルトのスタイルにする",
        "Short prose, set as typography": "短い文章をタイポグラフィとして組む",
        "Longer text and anything else": "長いテキストとその他すべて",
        "A quotation with its source": "出典付きの引用",
        "Code with highlighting and line numbers": "ハイライトと行番号付きのコード",
        "One number with its label": "ひとつの数値とそのラベル",
        "Bullet and numbered lists": "箇条書きと番号付きリスト",
        "A conversation between named people": "話者名のある会話",
        "Markdown and box-drawing tables": "Markdown と罫線の表",
        "Before / after, pros / cons": "前後の比較、長所と短所",
        "Mermaid flowcharts and arrow chains": "Mermaid のフローチャートと矢印でつないだ流れ",
        "Contacts, accounts and keys, field by field": "連絡先、アカウント、キーを項目ごとに",
        "Release notes: versions, dates and tagged changes": "リリースノート：バージョン、日付、分類された変更点",
        "Shell sessions: commands, output and errors": "シェルのセッション：コマンド、出力、エラー",
        "Diffs and patches: added and removed lines": "差分とパッチ：追加された行と削除された行",
        "Any text as a QR code": "任意のテキストを QR コードに",
        "Could not save this change.": "この変更を保存できませんでした。",
        "The card font cannot draw some characters in this text. Nothing was rendered or removed.": "このテキストには、カードのフォントで表示できない文字があります。カードは作成されず、テキストも削除されていません。",
        "There is no text to render.": "カードにするテキストがありません。",
        "This template or style is not available for this content.": "この内容には、このテンプレートまたはスタイルを使用できません。",
        "This card would not match the copied text exactly, so it was not made. Try another template.": "カードがコピーしたテキストと完全には一致しないため、作成しませんでした。別のテンプレートをお試しください。",
        "This text is too long for one QR code (keep it under about 2,900 English characters or 950 Chinese characters).": "テキストが長すぎて、1 つの QR コードに収まりません（英数字なら約 2,900 文字、漢字やかななら約 950 文字まで）。",
        "This content could not fit safely. Try a shorter excerpt; no text was silently removed.": "内容をカードに収めきれませんでした。短くしてお試しください。テキストが勝手に削られることはありません。",
        "Paper": "ペーパー",
        "Ink": "インク",
        "Poster": "ポスター",
        "Document": "ドキュメント",
        "Reading page": "読みもの",
        "Editorial column": "コラム",
        "Quote": "引用",
        "Book excerpt": "書籍の抜粋",
        "Statement": "ステートメント",
        "Code": "コード",
        "Terminal": "ターミナル",
        "Code notebook": "コードノート",
        "Statistic": "数値",
        "Big number": "大きな数字",
        "Metric strip": "指標バー",
        "List": "リスト",
        "Checklist": "チェックリスト",
        "Stacked steps": "ステップカード",
        "Conversation": "会話",
        "Chat bubbles": "吹き出し",
        "Transcript": "書き起こし",
        "Table": "表",
        "Data grid": "データグリッド",
        "Editorial ledger": "シンプルな表",
        "Comparison": "比較",
        "Side by side": "左右に並べる",
        "Split panels": "分割パネル",
        "Diagram": "図",
        "Flow": "フロー",
        "Blueprint": "設計図",
        "Info card": "情報カード",
        "Field list": "項目リスト",
        "Credentials": "認証情報",
        "Release notes": "リリースノート",
        "Release card": "リリースカード",
        "Timeline": "タイムライン",
        "Terminal session": "ターミナルセッション",
        "Night terminal": "夜のターミナル",
        "Command log": "コマンドログ",
        "Diff": "差分",
        "Review": "レビュー",
        "Night diff": "夜の差分",
        "Plain": "プレーン",
        "Card": "カード",
        "API keys": "API キー",
        "Well-known key formats: OpenAI, Anthropic, GitHub, AWS, Google, Slack, Stripe.": "よく知られたサービスのキー形式：OpenAI、Anthropic、GitHub、AWS、Google、Slack、Stripe。",
        "Private keys": "秘密鍵",
        "PEM and OpenSSH private key blocks.": "PEM や OpenSSH の秘密鍵ブロック。",
        "JSON Web Tokens": "JSON Web Token",
        "Tokens of the form eyJ….….….": "eyJ….….… 形式のトークン。",
        "Authorization headers": "Authorization ヘッダ",
        "The value of Authorization headers and Bearer tokens.": "Authorization ヘッダと Bearer トークンの値。",
        "Passwords in URLs": "URL 内のパスワード",
        "The password in URLs and database strings like scheme://user:password@host.": "scheme://user:password@host のような URL やデータベース接続文字列に含まれるパスワード。",
        "Passwords and secrets in settings": "設定内のパスワードと秘密情報",
        "The value after password=, token:, api_key=, 密码： and similar; the name stays.": "password=、token:、api_key=、密码： などの後ろの値。名前はそのまま残ります。",
        "Random-looking tokens": "ランダムな文字列",
        "Long random strings (20+ characters). Git hashes, UUIDs, words and plain links are left alone.": "20 文字以上のランダムな文字列。Git のハッシュ、UUID、単語、パスワードを含まないリンクは対象外です。",
        "Email addresses": "メールアドレス",
        "Email addresses.": "メールアドレス。",
        "Phone numbers": "電話番号",
        "Mainland China mobile numbers and international +… numbers.": "中国本土の携帯電話番号と、+ で始まる国際電話番号。",
        "ID card numbers": "身分証番号",
        "18-digit resident ID numbers with a valid checksum.": "チェックディジットが正しい 18 桁の中国の居民身分証番号。",
        "Bank card numbers": "カード番号",
        "13–19 digit card numbers that pass the Luhn check.": "Luhn チェックを通る 13〜19 桁のカード番号。",
    ]
}
