/**
 * Clipboard scenarios for the Studio (scripts/studio.ts) and the static gallery
 * (scripts/gallery.ts). Add a scenario here and both pick it up; `group` is the
 * sidebar heading (ungrouped ones go under 其他).
 */
export interface Scenario {
  readonly id: string;
  readonly title: string;
  readonly text: string;
  readonly group?: string;
}

export const SCENARIOS: readonly Scenario[] = [
  { id: "short", title: "一句话", text: "少即是多。", group: "文字" },
  { id: "slogan", title: "一句中文文案", text: "好的设计，是把复杂留给自己，把简单留给别人。", group: "文字" },
  { id: "english", title: "英文短句", text: "Make it work, make it right, make it fast.", group: "文字" },
  { id: "paragraph", title: "两段感想", text: "我们总以为效率来自更快的工具，其实更多来自更少的切换。把一件事做完再开始下一件，比同时开着十个窗口要快得多。\n\n今天就试试：关掉不用的标签页。", group: "文字" },
  { id: "emoji", title: "带 emoji 的消息", text: "周五下午茶到了 🍰☕️ 大家自取，顺便庆祝新版本上线 🎉", group: "文字" },
  { id: "quote", title: "带作者的引语", text: "“一个人只拥有此生此世是不够的，他还应该拥有诗意的世界。”——王小波", group: "引用" },
  { id: "quote-en", title: "英文引用块", text: "> Simplicity is prerequisite for reliability.\n— Edsger W. Dijkstra", group: "引用" },
  { id: "stat", title: "数据指标", text: "本季度活跃用户增长: 37%", group: "数据与列表" },
  { id: "list", title: "有序清单", text: "1. 先把问题写清楚\n2. 一次只改一个变量\n3. 量化结果再继续", group: "数据与列表" },
  { id: "bullets", title: "无序清单（英文）", text: "- Ship the native app\n- Record the release notes\n- Ask ten people to try it", group: "数据与列表" },
  { id: "code", title: "代码块", text: "```ts\nconst greet = (name: string) => {\n  return `Hello, ${name}!`;\n};\nconsole.log(greet(\"世界\"));\n```", group: "代码" },
  { id: "command", title: "终端命令", text: "git log --oneline -5 --author=anelikes", group: "代码" },
  { id: "code-python", title: "Python（中文注释）", text: "```python\nimport json\n\n# 读取配置并返回默认值 🎯\ndef load_config(path: str, default: dict | None = None) -> dict:\n    \"\"\"从文件加载配置；文件不存在时返回默认值。\"\"\"\n    try:\n        with open(path, encoding=\"utf-8\") as f:\n            return json.load(f)\n    except FileNotFoundError:\n        return default or {\"语言\": \"中文\", \"重试\": 3}\n```", group: "代码" },
  { id: "code-ts", title: "TypeScript", text: "```ts\ninterface Clip { id: number; text: string; pinned?: boolean }\n\nexport async function latest(clips: Clip[], limit = 5): Promise<Clip[]> {\n  const sorted = [...clips].sort((a, b) => b.id - a.id);\n  return sorted.filter((c) => !c.pinned).slice(0, limit);\n}\n```", group: "代码" },
  { id: "code-sql", title: "SQL 查询", text: "```sql\n-- 最近 7 天每个应用的复制次数\nSELECT app, COUNT(*) AS copies, MAX(created_at) AS last_seen\nFROM clipboard_history\nWHERE created_at >= NOW() - INTERVAL '7 days'\n  AND app <> 'Peesuto'\nGROUP BY app\nORDER BY copies DESC\nLIMIT 10;\n```", group: "代码" },
  { id: "code-shell", title: "终端会话", text: "$ bun install --frozen-lockfile\nbun install v1.3.11\n  + highlight.js@11.12.0\n$ bun test core/tests | tail -3\n 493 pass\n 0 fail\n$ git status --short\n M core/src/templates/compose.ts", group: "代码" },
  { id: "code-json", title: "JSON 配置", text: "{\n  \"name\": \"peesuto\",\n  \"version\": \"0.1.1\",\n  \"shortcuts\": { \"panel\": \"⌘⇧V\", \"card\": \"⌘⌥1\" },\n  \"privacy\": { \"offline\": true, \"rules\": [\"secrets\", \"email\"] },\n  \"theme\": null\n}", group: "代码" },
  { id: "code-go", title: "Go", text: "```go\npackage main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n)\n\n// 把每个单词的首字母大写\nfunc title(words []string) string {\n\tfor i, w := range words {\n\t\twords[i] = strings.ToUpper(w[:1]) + w[1:]\n\t}\n\treturn strings.Join(words, \" \")\n}\n\nfunc main() { fmt.Println(title([]string{\"hello\", \"gopher\"})) }\n```", group: "代码" },
  { id: "code-diff", title: "代码 diff", text: "```diff\ndiff --git a/core/src/render/fonts.ts b/core/src/render/fonts.ts\n@@ -1,4 +1,5 @@\n export const FONTS = {\n-  code: \"NotoSansSC\",\n+  code: \"PeesutoCode\",\n+  fallback: \"NotoSansSC\",\n   text: \"NotoSansSC\",\n };\n```", group: "代码" },
  { id: "chat", title: "带标签的对话", text: "用户: 这个快捷键在哪里改？\n助手: 设置 → 通用 → 快捷键，点一下就能录新的组合。\n用户: 找到了，谢谢！", group: "对话" },
  { id: "chat-app", title: "从聊天软件复制的记录（长，会滚动）", text: "nok\n2026年09月22日 22:10\n如果ty不去武汉的话我整一个看看\n\nshybee\n2026年09月23日  0:10\n@nok \n\nshybee\n2026年09月23日  0:10\n全聚德\n\nshybee\n2026年09月23日  0:11\n明天吃这个不\n\nnok\n2026年09月23日  8:20\n牛逼\n\nnok\n2026年09月23日  8:20\nok", group: "对话" },
  { id: "table", title: "Markdown 表格", text: "| 项目 | 状态 | 负责人 |\n| --- | --- | --- |\n| 原生界面 | 完成 | nok |\n| 模板渲染 | 验证中 | shybee |\n| 签名公证 | 待证书 | — |", group: "数据与列表" },
  { id: "comparison", title: "前后对比", text: "之前:\n许多零散入口\n\n手动排版\n\n之后:\n一个明确动作\n\n自动选择模板", group: "数据与列表" },
  { id: "markdown", title: "Markdown 笔记", text: "# 周会纪要\n\n本周完成了原生版迁移，**所有测试通过**。\n\n- 文字模板上线\n- 聊天记录可以滚动\n\n## 下周\n\n准备第一次签名发布。", group: "文档" },
  { id: "long", title: "长文（超过一屏）", text: Array.from({ length: 6 }, (_, i) => `第 ${i + 1} 段。把复杂的想法讲清楚，需要先把它想清楚，再删掉所有不必要的部分，最后留下的每一句话都应该有它存在的理由。写作如此，做产品也如此。`).join("\n\n"), group: "文字" },
  { id: "mermaid-decision", title: "Mermaid 判断流程", text: "```mermaid\nflowchart TD\n    A([用户复制文字]) --> B{有明确结构吗?}\n    B -->|有| C[专门模板]\n    B -->|没有| D{够短吗?}\n    D -->|是| E[文字模板]\n    D -->|否| F[文档模板]\n    C --> G([渲染并粘贴])\n    E --> G\n    F --> G\n```", group: "流程图" },
  { id: "mermaid-cycle", title: "Mermaid 带回环", text: "flowchart TD\n  A[写代码] --> B[跑测试]\n  B -- 失败 --> A\n  B -- 通过 --> C[提交]\n  C -.-> D[(发布)]", group: "流程图" },
  { id: "mermaid-lr", title: "Mermaid 横向流水线", text: "graph LR\n  clip[剪贴板] --> parse[解析] --> decide[选模板] --> layout[排版] --> render[渲染]", group: "流程图" },
  { id: "arrow-chain", title: "一行箭头链", text: "需求 → 设计 → 开发 → 测试 → 上线", group: "流程图" },
  // 隐私：以下密钥全是编造的（FAKE），只用来看脱敏效果，任何服务都不认。
  { id: "privacy-env", title: "带密钥的配置片段", text: "# 本地开发配置\nOPENAI_API_KEY=sk-proj-FAKEfake0000FAKEfake1111FAKE\nDATABASE_URL=postgres://app:fake-pass-123@db.internal:5432/app\nDEBUG=true", group: "隐私" },
  { id: "privacy-chat", title: "消息里夹着令牌与密码", text: "我把测试环境的登录信息发你：\n账号 demo，密码：Fake#2026pass\n接口加请求头 Authorization: Bearer FAKEtoken0000fake1111FAKE 就行，用完记得换掉。", group: "隐私" },
  { id: "privacy-contact", title: "联系方式（个人信息规则默认关闭）", text: "周五评审改到 3 点，有问题找小王：13800000000，wang.fake@example.com。GitHub 令牌 ghp_FAKEfakeFAKEfakeFAKEfakeFAKEfake0000 已作废。", group: "隐私" },
  { id: "info-contact", title: "联系方式（信息卡）", text: "张三\n手机：13800138000\n邮箱：zhangsan@example.com\n地址：杭州市西湖区文三路 90 号", group: "信息卡" },
  { id: "info-bare-contact", title: "没有标签的联系方式（信息卡，图标代替标签）", text: "张三\n13800138000\nzhangsan@example.com\n杭州市西湖区文三路 90 号", group: "信息卡" },
  { id: "code-keymap", title: "带 ⌘⌥ 的快捷键配置 JSON", text: "{\n  \"paste\": \"⌘⇧V\",\n  \"card\": \"⌘⌥1\",\n  \"pin\": \"⌘⌥5\"\n}", group: "代码" },
  { id: "info-account", title: "测试账号与密钥（信息卡）", text: "测试环境账号\n用户名: admin\n密码: Fake#2026pass\nAPI Key: sk-proj-FAKEfake0000FAKEfake1111\nHost: https://staging.example.com", group: "隐私" },
  { id: "changelog-md", title: "发布说明（Markdown）", text: "## v1.2.0 — 2026-09-24\n### Added\n- Signature footer on every card\n- Release notes become cards\n### Fixed\n- Long code lines wrap instead of shrinking\n### Security\n- Secrets are redacted before a model sees them", group: "更新日志" },
  { id: "changelog-zh", title: "更新日志（中文、多个版本）", text: "## 1.3.0 (2026-10-01)\n新增：\n- 卡片签名\n- 更新日志模板\n修复：\n- 长代码行自动换行\n\n## 1.2.0 (2026-09-20)\n变更：\n- 字号不低于手机可读下限", group: "更新日志" },
  { id: "changelog-commits", title: "提交摘要式发布说明", text: "v1.2.0\n- feat: add signature footer\n- fix: wrap long code lines\n- docs: template spec", group: "更新日志" },
  { id: "terminal-push", title: "终端会话（报错与退出码）", text: "$ bun test core/tests | tail -2\n 566 pass\n 0 fail\n$ git push origin main\nTo github.com:example/peesuto.git\n ! [rejected]        main -> main (fetch first)\nerror: failed to push some refs to 'github.com:example/peesuto.git'\n[exit 1]", group: "终端" },
  { id: "terminal-zh", title: "终端会话（中文路径与输出）", text: "nya@mbp:~/项目$ npm run 构建\n> peesuto@0.2.0 构建\n> tsc && vite build\nnpm WARN deprecated 旧的依赖已弃用\n✓ 构建完成，用时 3.2 秒\nnya@mbp:~/项目$ ./部署.sh\nbash: ./部署.sh: Permission denied", group: "终端" },
  { id: "terminal-powershell", title: "PowerShell 会话", text: "PS C:\\Users\\nya> winget --version\nv1.9.25200\nPS C:\\Users\\nya> peesuto\npeesuto : The term 'peesuto' is not recognized as the name of a cmdlet, function, script file, or operable program.", group: "终端" },
  { id: "diff-git", title: "git diff（两个文件、重命名与二进制）", text: "diff --git a/core/src/render/fonts.ts b/core/src/render/fonts.ts\nindex 3f2a1c9..8b7e4d0 100644\n--- a/core/src/render/fonts.ts\n+++ b/core/src/render/fonts.ts\n@@ -1,6 +1,7 @@ import { join } from \"node:path\";\n export const FONTS = {\n-  code: \"NotoSansSC\",\n+  code: \"PeesutoCode\",\n+  fallback: \"NotoSansSC\",\n   text: \"NotoSansSC\",\n };\n \ndiff --git a/docs/old-name.md b/docs/guide.md\nsimilarity index 92%\nrename from docs/old-name.md\nrename to docs/guide.md\n--- a/docs/old-name.md\n+++ b/docs/guide.md\n@@ -1,2 +1,2 @@\n-# Old name\n+# Guide\n Welcome.\ndiff --git a/assets/logo.png b/assets/logo.png\nnew file mode 100644\nBinary files /dev/null and b/assets/logo.png differ", group: "代码差异" },
  { id: "diff-zh", title: "diff -u（中文文档）", text: "--- a/文档/说明.md\n+++ b/文档/说明.md\n@@ -3,4 +3,5 @@\n ## 安装\n-下载 DMG，拖进应用程序文件夹。\n+用 Homebrew 安装：brew install --cask peesuto\n+或者下载 DMG，拖进应用程序文件夹。\n \n 首次打开时需要授予辅助功能权限。", group: "代码差异" },
  { id: "diff-show", title: "git show（提交信息在上）", text: "commit 8d829cc1f2e3a4b5c6d7e8f90a1b2c3d4e5f6a7b (HEAD -> main, origin/main)\nAuthor: 林小雨 <lin@example.com>\nDate:   Wed Sep 24 10:12:03 2026 +0800\n\n    fix(fonts): fall back to Noto Sans SC for Chinese\n\n    PingFang is not bundled, so cards rendered on CI had tofu.\n\ndiff --git a/core/src/render/fonts.ts b/core/src/render/fonts.ts\nindex 3f2a1c9..8b7e4d0 100644\n--- a/core/src/render/fonts.ts\n+++ b/core/src/render/fonts.ts\n@@ -12,3 +12,3 @@ export const FONTS = {\n   latin: \"Peesuto Text\",\n-  cjk: \"PingFang SC\",\n+  cjk: \"Noto Sans SC\",\n   mono: \"Peesuto Code\",", group: "代码差异" },
  { id: "diff-patch", title: "git format-patch（邮件头）", text: "From 8d829cc1f2e3a4b5c6d7e8f90a1b2c3d4e5f6a7b Mon Sep 17 00:00:00 2001\nFrom: Lin <lin@example.com>\nDate: Wed, 24 Sep 2026 10:12:03 +0800\nSubject: [PATCH] docs: install with Homebrew\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\n---\n README.md | 3 ++-\n 1 file changed, 2 insertions(+), 1 deletion(-)\n\ndiff --git a/README.md b/README.md\nindex 1a2b3c4..5d6e7f8 100644\n--- a/README.md\n+++ b/README.md\n@@ -3,2 +3,3 @@\n ## Install\n-Download the DMG.\n+brew install --cask anelikes/tap/peesuto\n+or download the DMG.\n-- \n2.50.1 (Apple Git-155)\n", group: "代码差异" },
  { id: "error-node", title: "Node 报错与调用栈", text: "Error: ENOENT: no such file or directory, open '/srv/paste/config/actions.json'\n    at Object.openSync (node:fs:601:3)\n    at readFileSync (node:fs:469:35)\n    at loadActions (/srv/paste/core/src/actions/load.ts:18:22)\n    at async runAction (/srv/paste/core/src/actions/run.ts:41:19)\n    at async handle (/srv/paste/core/src/daemon/server.ts:77:12)", group: "报错" },
  { id: "error-python", title: "Python Traceback（错误在最后）", text: "Traceback (most recent call last):\n  File \"/srv/etl/run.py\", line 88, in <module>\n    main()\n  File \"/srv/etl/parse.py\", line 27, in parse\n    return int(cells[2])\n  File \"/usr/lib/python3.12/json/__init__.py\", line 293, in load\n    return loads(fp.read())\nValueError: invalid literal for int() with base 10: '1,204'", group: "报错" },
  { id: "error-java-zh", title: "Java 异常（中文信息、Caused by）", text: "Exception in thread \"main\" java.lang.IllegalStateException: 订单状态不能从「已发货」改回「待付款」\n\tat com.example.shop.OrderService.transition(OrderService.java:88)\n\tat com.example.shop.OrderController.cancel(OrderController.java:41)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:897)\nCaused by: java.sql.SQLException: 连接已关闭\n\tat com.zaxxer.hikari.pool.ProxyConnection.checkClosed(ProxyConnection.java:506)\n\t... 3 more", group: "报错" },
  { id: "error-ruby", title: "Ruby 报错（gems 调暗）", text: "app/services/invoice.rb:18:in 'Integer#/': divided by 0 (ZeroDivisionError)\n\tfrom app/services/invoice.rb:18:in 'Invoice#average'\n\tfrom /usr/local/bundle/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:121:in 'block in ActiveSupport::Callbacks#run_callbacks'\n\tfrom app/jobs/monthly_report_job.rb:9:in 'MonthlyReportJob#perform'\n\tfrom bin/report:4:in '<main>'", group: "报错" },
  { id: "error-php", title: "PHP Fatal error（vendor 调暗）", text: "PHP Fatal error:  Uncaught InvalidArgumentException: 优惠券已过期 in /var/www/shop/src/Coupon.php:42\nStack trace:\n#0 /var/www/shop/src/Cart.php(88): App\\Coupon->apply(Object(App\\Cart))\n#1 /var/www/shop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Cart->checkout()\n#2 [internal function]: Illuminate\\Routing\\Controller->callAction()\n#3 {main}\n  thrown in /var/www/shop/src/Coupon.php on line 42", group: "报错" },
  { id: "error-go", title: "Go panic", text: "panic: runtime error: index out of range [5] with length 3\n\ngoroutine 1 [running]:\nmain.main()\n\t/tmp/sandbox/prog.go:8 +0x1d\nexit status 2", group: "报错" },
  { id: "timeline-day", title: "一天的日程（中文）", text: "周五发布日程\n09:00 冻结代码\n10:30–11:00 回归测试，覆盖所有模板\n14:00 提交公证\n下午5点 发布 0.3.0 🎉", group: "日程" },
  { id: "timeline-en", title: "Event agenda (English)", text: "Launch day\n9:00am - Doors open\n9:30 am | Keynote: What's next for Peesuto\n12:00 Lunch on the terrace\n2pm Workshops: templates, privacy rules and the model decider\n6:30pm Party", group: "日程" },
  { id: "timeline-roadmap", title: "路线图（季度与日期）", text: "## Roadmap\n- 2026-09-24 v0.2.0 released\n- 2026-10-15 Homebrew cask\n- Q1 2027 Windows beta\n- H2 2027 Template workshop", group: "日程" },
  { id: "log-not-timeline", title: "日志（不是日程）", text: "10:21 INFO render queued id=8f1c2a\n10:21 WARN frame took 1210 ms\n10:22 ERROR upload failed status=503", group: "日程" },
  { id: "stats-en", title: "Weekly metrics (deltas)", text: "Weekly metrics\nDAU: 12,480 (+8%)\nRevenue: $48.2k (−3.1% WoW)\nChurn: 2.4% ↓0.3pp\nNPS: 61\nStars: 1,204 (+96)", group: "数据与列表" },
  { id: "stats-zh", title: "本周数据（多项指标）", text: "本周数据\n日活：12,480（+8%）\n收入：¥32.5万（-4%）\n转化率：3.2%\n新用户：1,860 人", group: "数据与列表" },
  { id: "lyrics-zh", title: "中文歌词（两段）", text: "旧站台的白铃兰\n从那年夏天开到现在\n你折好的纸飞机\n还停在我窗前的风里\n\n踩着单车穿过雨巷\n我听见心跳慢慢*靠近*", group: "歌词" },
  { id: "lyrics-ja", title: "日文歌词（JIZURA 记法：/ 切分、*强调*、!）", text: "夜明けの色を/覚えてる\n*透明*な傘をたたんで\n坂道の途中で笑った!\n\nまだ眠い町の灯り", group: "歌词" },
  { id: "lyrics-en", title: "English lyrics (stanzas, emphasis)", text: "I remember the dawn\nPaper lanterns on the river\nWe were counting every bridge back home\n\nOh, *stay awake* with me\nStay awake with me!", group: "歌词" },
  { id: "lyrics-poem", title: "古诗（竖排：纸面风格）", text: "静夜思\n李白\n床前明月光，疑是地上霜。\n举头望明月，低头思故乡。", group: "歌词" },
  { id: "lyrics-lrc", title: "LRC 歌词（带时间轴）", text: "[ti:纸飞机]\n[ar:Peesuto]\n[00:12.34]旧站台的白铃兰\n[00:15.80]从那年夏天开到现在\n[00:19.20]你折好的纸飞机\n[00:22.60]还停在我窗前的风里", group: "歌词" },
  { id: "lyrics-note", title: "注释与段落标签（lyric|note、[Chorus]）", text: "[Chorus]\nLa la la|hum along\nKeep the porch light on\nKeep the porch light on!", group: "歌词" },
  { id: "short-lines-not-lyrics", title: "短行清单（不是歌词）", text: "Buy milk\nCall mom\nFix bike\nPay rent", group: "歌词" },
  { id: "info-numbers", title: "数字多但属于信息卡（电话、订单号）", text: "订单信息\n订单号：202609240001\n金额：¥128\n电话：13800138000", group: "信息卡" },
  { id: "arrow-branches", title: "多行箭头链（分支与汇合）", text: "登录 -> 首页 -> 设置\n首页 -> 历史\n历史 -> 详情 -> 设置", group: "流程图" },
  { id: "qr-url", title: "网址（用 ⌘⌥4 转二维码）", text: "https://peesuto.com/download?ref=clipboard", group: "二维码" },
  { id: "qr-note", title: "多行留言（二维码不参与自动选择）", text: "明天下午三点，老地方见。\n记得带上那本《诗意的世界》🎉", group: "二维码" },
];
