#!/usr/bin/env bun
/**
 * JIZURA as a dependency: the engine source at the commit jizura.json pins,
 * built into vendor/jizura/ exactly as its own build.py builds the page's
 * script, and checked against that pin.
 *
 *   bun scripts/jizura.ts            fetch the pinned commit into .work/jizura-src (reused when its
 *                                     HEAD is the pin), then write vendor/jizura/{jizura.js,LICENSE,catalog.json}
 *   bun scripts/jizura.ts --check    rebuild in memory from the pinned source and compare with the
 *                                     committed files, byte for byte; exit 1 on any difference
 *   --source <dir>                   use this checkout instead (its HEAD must be the pin)
 *
 * jizura.js is src/*.js in sorted order joined with "\n" and `@VERSION@`
 * replaced by VERSION, which is what build.py puts in every edition's
 * <script> (dev/www/jizura.js is the same join without the replacement),
 * under a header naming the commit and the MIT notice. Nothing in it is
 * edited: the adaptation (shims, fonts, seeding, timing) is core/src/jizura/.
 * catalog.json lists the styles, moods and part sets with JIZURA's own names
 * (Japanese, from the engine) and the labels of its English and Simplified
 * Chinese editions (app/english.js, app/i18n_zh_hans.py, app/chinese_hans.js).
 *
 * The fetch is a sparse, blobless, depth-1 fetch of one commit (src/, app/,
 * LICENSE, VERSION: a few MB), so --check is cheap enough for CI.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import vm from "node:vm";

const REPO_ROOT = resolve(import.meta.dir, "..");
const PIN_PATH = join(REPO_ROOT, "jizura.json");
const VENDOR = join(REPO_ROOT, "vendor/jizura");
const DEFAULT_SOURCE = join(REPO_ROOT, ".work/jizura-src");
const SPARSE = ["src", "app", "LICENSE", "VERSION"];

interface Pin { readonly repo: string; readonly commit: string; readonly version: string; readonly note?: string }

function fail(message: string): never {
  console.error(`jizura: ${message}`);
  process.exit(1);
}

export function readPin(path = PIN_PATH): Pin {
  const pin = JSON.parse(readFileSync(path, "utf8")) as Pin;
  if (!/^https:\/\//.test(pin.repo)) fail(`${path}: repo must be an https URL`);
  if (!/^[0-9a-f]{40}$/.test(pin.commit)) fail(`${path}: commit must be a full 40-character sha`);
  if (!/^\d+\.\d+\.\d+$/.test(pin.version)) fail(`${path}: version must be x.y.z`);
  return pin;
}

async function git(cwd: string, ...args: string[]): Promise<string> {
  const p = Bun.spawn(["git", "-C", cwd, ...args], { stdin: "ignore", stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([new Response(p.stdout).text(), new Response(p.stderr).text(), p.exited]);
  if (code !== 0) throw new Error(`git ${args.join(" ")}: ${err.trim() || `exit ${code}`}`);
  return out.trim();
}

async function headOf(dir: string): Promise<string | null> {
  try { return await git(dir, "rev-parse", "HEAD"); } catch { return null; }
}

/** A checkout of the pinned commit (fetched sparsely when `dir` has none). */
async function source(pin: Pin, dir: string, explicit: boolean): Promise<string> {
  const head = existsSync(dir) ? await headOf(dir) : null;
  if (head === pin.commit) return dir;
  if (explicit) fail(`${dir} is at ${head ?? "no commit"}, not the pinned ${pin.commit}`);
  if (existsSync(dir) && head !== null) {
    // Our own sparse checkout from an earlier pin: move it.
    console.error(`jizura: ${dir} is at ${head.slice(0, 12)}; fetching ${pin.commit.slice(0, 12)}`);
  } else {
    mkdirSync(dir, { recursive: true });
    await git(dir, "init", "-q");
    await git(dir, "remote", "add", "origin", pin.repo);
  }
  await git(dir, "sparse-checkout", "set", "--no-cone", ...SPARSE.map((p) => `/${p}${p.includes(".") || p === "LICENSE" || p === "VERSION" ? "" : "/"}`));
  await git(dir, "fetch", "-q", "--depth", "1", "--filter=blob:none", "origin", pin.commit);
  await git(dir, "-c", "advice.detachedHead=false", "checkout", "-q", "--force", pin.commit);
  const now = await headOf(dir);
  if (now !== pin.commit) fail(`fetched ${dir} but HEAD is ${now}`);
  return dir;
}

/* ---- build ------------------------------------------------------------------ */

export interface Built { readonly js: string; readonly license: string; readonly catalog: string }

export function header(pin: Pin, files: readonly string[]): string {
  return [
    "/*!",
    ` * JIZURA ${pin.version} — lyric motion engine by hakoniwa (852wa)`,
    ` * ${pin.repo} at ${pin.commit}`,
    " *",
    " * Copyright (c) 2026 hakoniwa. MIT License: the full text is in vendor/jizura/LICENSE",
    " * (and in Peesuto's NOTICE). Used in Peesuto with the author's permission; JIZURA is",
    " * credited in the license.",
    " *",
    ` * Generated by scripts/jizura.ts from jizura.json: the ${files.length} files of src/ in sorted order, joined`,
    " * with \"\\n\" and @VERSION@ replaced by VERSION, as JIZURA's build.py builds each edition's",
    " * <script>. Unmodified; do not edit (bun scripts/jizura.ts --check verifies it).",
    " */",
    "",
  ].join("\n");
}

export function build(pin: Pin, dir: string): Built {
  const version = readFileSync(join(dir, "VERSION"), "utf8").trim();
  if (version !== pin.version) fail(`VERSION at ${pin.commit.slice(0, 12)} is ${version}, jizura.json says ${pin.version}`);
  // build.py: sorted(glob.glob('src/*.js')), '\n'.join(read(f) ...), script.replace('@VERSION@', VERSION).
  const files = readdirSync(join(dir, "src")).filter((f) => f.endsWith(".js")).sort();
  if (files.length === 0) fail(`${dir}/src has no .js files`);
  const joined = files.map((f) => readFileSync(join(dir, "src", f), "utf8")).join("\n").replaceAll("@VERSION@", version);
  const js = header(pin, files) + joined;
  const license = readFileSync(join(dir, "LICENSE"), "utf8");
  const catalog = `${JSON.stringify(extractCatalog(joined, dir), null, 2)}\n`;
  return { js, license, catalog };
}

/* ---- catalog ---------------------------------------------------------------- */

/** A canvas that draws nothing: enough for the engine's top level to evaluate. */
function stubCanvas(): unknown {
  const fn: ProxyHandler<object> = {
    get: (_t, key) => (key === "width" || key === "height" ? 1 : key === "measureText" ? () => ({ width: 1 }) : typeof key === "symbol" ? undefined : new Proxy(() => stub, fn)),
    apply: () => stub,
  };
  const stub: object = new Proxy(function () {}, fn);
  return { width: 1, height: 1, getContext: () => stub };
}

interface Labels { en?: readonly [string, string]; "zh-Hans"?: readonly [string, string] }

function englishLabels(dir: string): { styles: Record<string, [string, string]>; moods: Record<string, string> } {
  const src = readFileSync(join(dir, "app/english.js"), "utf8");
  const styles: Record<string, [string, string]> = {};
  const block = /const styles = \{([\s\S]*?)\n\s*\};/.exec(src)?.[1] ?? "";
  for (const m of block.matchAll(/(\w+): \['((?:[^'\\]|\\.)*)', '((?:[^'\\]|\\.)*)'\]/g)) styles[m[1]!] = [m[2]!, m[3]!];
  for (const m of src.matchAll(/const S = (\{"hr[^\n]*\});/g)) Object.assign(styles, JSON.parse(m[1]!) as Record<string, [string, string]>);
  const moods: Record<string, string> = {};
  const moodBlock = /Object\.entries\(\{(glitch:[^}]*)\}\)\) J\.MOODS\[key\]\.name/.exec(src)?.[1] ?? "";
  for (const m of moodBlock.matchAll(/(\w+):'((?:[^'\\]|\\.)*)'/g)) moods[m[1]!] = m[2]!;
  const horror = /J\.MOODS\.horror\.name = "([^"]*)"/.exec(src)?.[1];
  if (horror) moods.horror = horror;
  return { styles, moods };
}

function simplifiedChineseLabels(dir: string): { styles: Record<string, [string, string]>; moods: Record<string, string> } {
  const py = readFileSync(join(dir, "app/i18n_zh_hans.py"), "utf8");
  const styles: Record<string, [string, string]> = {};
  const block = /\nSTYLES = \{([\s\S]*?)\n\}/.exec(py)?.[1] ?? "";
  for (const m of block.matchAll(/'(\w+)': \('((?:[^'\\]|\\.)*)', '((?:[^'\\]|\\.)*)'\)/g)) styles[m[1]!] = [m[2]!, m[3]!];
  const moods: Record<string, string> = {};
  const moodBlock = /\nMOODS = \{([\s\S]*?)\n\}/.exec(py)?.[1] ?? "";
  for (const m of moodBlock.matchAll(/'(\w+)': '((?:[^'\\]|\\.)*)'/g)) moods[m[1]!] = m[2]!;
  const js = readFileSync(join(dir, "app/chinese_hans.js"), "utf8");
  for (const m of js.matchAll(/const S = (\{"hr[^\n]*\});/g)) Object.assign(styles, JSON.parse(m[1]!) as Record<string, [string, string]>);
  const horror = /J\.MOODS\.horror\.name = "([^"]*)"/.exec(js)?.[1];
  if (horror) moods.horror = horror;
  return { styles, moods };
}

interface JizuraGlobal {
  STYLES: Record<string, { name: string; desc: string; set?: string; extra?: boolean; wa?: boolean; moods?: string[] }>;
  STYLE_ORDER: string[];
  MOODS: Record<string, { name: string; set?: string; styles?: string[] | null }>;
  SETS: Record<string, { on: boolean }>;
  GROUP_KEYS: string[];
  order(group: string): string[];
  registry(group: string): Record<string, { name: string; set?: string; extra?: boolean; wa?: boolean }>;
}

export function extractCatalog(joined: string, dir: string): unknown {
  const window: Record<string, unknown> = {};
  const document = { createElement: () => stubCanvas(), getElementById: () => null, head: null, body: null, documentElement: { lang: "ja" }, fonts: { load: async () => [], add() {}, check: () => true } };
  const context = vm.createContext({ window, document, console: { log() {}, warn() {}, error() {} } });
  vm.runInContext(joined, context, { filename: "jizura.js" });
  const J = window.J as JizuraGlobal;
  const en = englishLabels(dir), zh = simplifiedChineseLabels(dir);
  const label = (table: { styles: Record<string, [string, string]> }, key: string) => table.styles[key];
  const styles = J.STYLE_ORDER.map((key) => {
    const s = J.STYLES[key]!;
    const labels: Labels = { ...(label(en, key) ? { en: label(en, key)! } : {}), ...(label(zh, key) ? { "zh-Hans": label(zh, key)! } : {}) };
    return { key, ja: [s.name, s.desc], ...labels, set: s.set ?? null, extra: Boolean(s.extra), wa: Boolean(s.wa), moods: s.moods ?? [] };
  });
  const moods = Object.entries(J.MOODS).map(([key, m]) => ({ key, ja: m.name, en: en.moods[key] ?? null, "zh-Hans": zh.moods[key] ?? null, set: m.set ?? null }));
  const parts: Record<string, { total: number; sets: Record<string, number>; extra: number; wa: number }> = {};
  for (const g of J.GROUP_KEYS) {
    const reg = J.registry(g), keys = J.order(g);
    const sets: Record<string, number> = {};
    let extra = 0, wa = 0;
    for (const k of keys) {
      const d = reg[k];
      if (!d) continue;
      if (d.set) sets[d.set] = (sets[d.set] ?? 0) + 1;
      if (d.extra) extra++;
      if (d.wa) wa++;
    }
    parts[g] = { total: keys.length, sets, extra, wa };
  }
  return { sets: Object.fromEntries(Object.entries(J.SETS).map(([k, v]) => [k, { on: v.on }])), styles, moods, parts };
}

/* ---- main ------------------------------------------------------------------- */

const OUTPUTS = (b: Built) => [["jizura.js", b.js], ["LICENSE", b.license], ["catalog.json", b.catalog]] as const;

if (import.meta.main) {
  const argv = process.argv.slice(2);
  const check = argv.includes("--check");
  const at = argv.indexOf("--source");
  const explicit = at >= 0 ? resolve(argv[at + 1] ?? fail("--source needs a directory")) : undefined;
  for (const [i, a] of argv.entries()) if (a !== "--check" && a !== "--source" && argv[i - 1] !== "--source") fail(`unknown argument ${a} (flags: --check, --source <dir>)`);
  const pin = readPin();
  let dir: string;
  try { dir = await source(pin, explicit ?? DEFAULT_SOURCE, explicit !== undefined); }
  catch (e) { fail(e instanceof Error ? e.message : String(e)); }
  const built = build(pin, dir);
  if (check) {
    const bad: string[] = [];
    for (const [name, want] of OUTPUTS(built)) {
      const path = join(VENDOR, name);
      const have = existsSync(path) ? readFileSync(path, "utf8") : null;
      if (have !== want) bad.push(have === null ? `${name} is missing` : `${name} differs from a build of ${pin.commit.slice(0, 12)}`);
    }
    if (bad.length) fail(`${bad.join("; ")}. Run \`bun scripts/jizura.ts\` and commit vendor/jizura/.`);
    console.log(`jizura: vendor/jizura matches ${pin.repo} at ${pin.commit.slice(0, 12)} (${pin.version})`);
  } else {
    mkdirSync(VENDOR, { recursive: true });
    for (const [name, text] of OUTPUTS(built)) writeFileSync(join(VENDOR, name), text);
    console.log(`jizura: wrote vendor/jizura/ from ${pin.commit.slice(0, 12)} (${pin.version}): jizura.js ${(Buffer.byteLength(built.js) / 1024).toFixed(0)} KB`);
  }
}
