/** The measurement charset (core/src/render/charset.txt) is generated by scripts/charset.ts. */
import { expect, test } from "bun:test";
import { charset, CHARSET_PATH } from "../../scripts/charset.ts";

test("charset.txt is what scripts/charset.ts writes, with no newline", async () => {
  const text = await Bun.file(CHARSET_PATH).text();
  expect(text === charset()).toBe(true);
  expect(text).not.toContain("\n");
  expect(new Set(text).size).toBe([...text].length);
});

test("Chinese and Japanese text measures against the cached bake: no character outside the charset", async () => {
  const have = new Set(await Bun.file(CHARSET_PATH).text());
  // Sample lines written for this test, and the marks and forms that text around them uses.
  const outside = (s: string) => [...s].filter((c) => c.codePointAt(0)! > 126 && c !== "\n" && !have.has(c));
  expect(outside("夜明けの色を覚えてる\n透明な傘をたたんで\nねえ、まだ間に合うかな\n駅のホームで、知らない人と同じ歌を口ずさんでいた。")).toEqual([]);
  expect(outside("晚风吹亮月光，我们慢慢走回家。路灯一盏盏醒来！")).toEqual([]);
  expect(outside("「」『』・〜ー々　♪※①０９ＡＺａｚ（）【】《》…—")).toEqual([]);
});
